### ISSUE TITLE
Invalid json in export on some distributions

### ISSUE THREAD

**Issue by mowgli** [GothenburgBitFactory/taskwarrior#2689] opened 2021-11-21 22:44 UTC
Running `task xxxx export` on two different installationes (debian and gentoo) with the same version (2.6.1) produced invalide json on gentoo (`…,"depends":["["yyy"]"],…`) while doing correct on debian (`…,"depends":["[\"yyy\"]"],…`).

I checked the patches applied on debian side but they does not show anything that would expect that differences.

**Comment by mowgli** [comment] 2021-11-21 23:22
I tracket this down further. For some reasons, there is some strange entry in completed.data. On gentoo, I get:
```json
[dep_["1b4b7021-b672-403b-8ca6-1c23c74e1626"]:"x" depends:"&open;\"1b4b7021-b672-403b-8ca6-1c23c74e1626\"&close;" description:"XXX" due:"1635721200" end:"1635616030" entry:"1634032181" modified:"1635616030" priority:"M" project:"XXX" status:"completed" uuid:"be188c87-0da6-4d4f-a5e0-beaf8b9555da"]
```

and  on my debian box, I have:
```jspn
[dep_[\"1b4b7021-b672-403b-8ca6-1c23c74e1626\"]:"x" depends:"&open;\\\"1b4b7021-b672-403b-8ca6-1c23c74e1626\\\"&close;" description:"XXX" due:"1635721200" end:"1635616030" entry:"1634032181" modified:"1635616030" priority:"M" project:"XXX" status:"completed" uuid:"be188c87-0da6-4d4f-a5e0-beaf8b9555da"]
```

As the data is strictly synced via task server, I have no idea why they are different and why they are somewhat broken.

Any idea how:
* that could hapen?
* that could be fixed?

(Not that secret task but I redacted the private stuff out.)

**Comment by RonMcKay** [comment] 2021-11-22 11:23
I can confirm, I also noticed some very strange data formatting in my pending.data. I am also using a task server for syncing. I mostly have Ubuntu/Debian on my machines, except for one smartphone where I use termux for viewing and sometimes editing my tasks. All of my machines are running taskwarrior 2.6.1 (build from source).

On Ubuntu the entry in my pending.data looks as follows:
`[dep_4fd6182b-143d-4011-bed4-e4f0f340c964:"x" dep_[\"24e2b930-dd35-46b5-b55e-578e94d770a6\":"x" dep_\"4fd6182b-143d-4011-bed4-e4f0f340c964\"]:"x" depends:"4fd6182b-143d-4011-bed4-e4f0f340c964,&open;\\\"24e2b930-dd35-46b5-b55e-578e94d770a6\\\",\\\"4fd6182b-143d-4011-bed4-e4f0f340c964\\\"&close;" description:"Some description" due:"1639159200" entry:"1628164649" modified:"1637577388" scheduled:"1633644000" status:"pending" uuid:"1f959b78-6b19-4a3d-8bc7-40551b7451f7"]`

While on termux it looks like:

`[dep_[\"4fd6182b-143d-4011-bed4-e4f0f340c964\":"x" dep_\"[\"24e2b930-dd35-46b5-b55e-578e94d770a6\"\":"x" dep_\"\"4fd6182b-143d-4011-bed4-e4f0f340c964\"]\"]:"x" depends:"&open;\\\"4fd6182b-143d-4011-bed4-e4f0f340c964\\\",\\\"&open;\\\"24e2b930-dd35-46b5-b55e-578e94d770a6\\\"\\\",\\\"\\\"4fd6182b-143d-4011-bed4-e4f0f340c964\\\"&close;\\\"&close;" description:"Some description" due:"1639159200" entry:"1628164649" modified:"1637577388" scheduled:"1633644000" status:"pending" uuid:"1f959b78-6b19-4a3d-8bc7-40551b7451f7"]`

When running `task` on ubuntu the task shows correctly as being blocked, while on termux it does not show as blocked even though the info card of the task shows the dependency. It also seems like there was a back and forth between the two installations, which caused the mess with the dependency data.

**Comment by tbabej** [comment] 2021-11-22 14:30
From what I'm hearing here the issue here are not different builds, but likely some sync problem. Am I correct in assuming all tasks that exhibit problems here have dependencies? (from the posted examples it looks so, but it would be nice to verify)

**Comment by RonMcKay** [comment] 2021-11-22 14:34
Yes, that only happens for tasks with dependencies in my case.
I am not really sure if that happened also before my upgrade to tw 2.6.1, at least I did not notice something similar.

**Comment by mowgli** [comment] 2021-11-22 21:03
Same for me, only for tasks with dependencies.

**Comment by mowgli** [comment] 2021-11-22 21:05
And it came up when using taskwiki. That has another bug currently to not respect scopes but I don't think, this is related to this bug.

**Comment by tbabej** [comment] 2021-12-05 04:46
@mowgli @RonMcKay Klaus, Phillip, are you self-hosting taskd, or perhaps using one of the public servers with a web interface (i.e. inthe.am)?

**Comment by tbabej** [comment] 2021-12-05 04:50
Scratch that question, I can reproduce the problem.

**Comment by tbabej** [comment] 2021-12-05 05:05
This seems to happen when 2.6.0+ client receives the updates from the server. The data on the server still seems intact, as I verified a 2.5.3 client can receive the same data without problems.

**Comment by RonMcKay** [comment] 2021-12-05 08:54
> This seems to happen when 2.6.0+ client receives the updates from the server. The data on the server still seems intact, as I verified a 2.5.3 client can receive the same data without problems.

I am self-hosting and it is the same for me. The data on the server seems to be fine.

**Comment by tbabej** [comment] 2021-12-05 23:46
@RonMcKay I'm assuming you're running `taskd` 1.1.0?

**Comment by RonMcKay** [comment] 2021-12-06 06:23
> @RonMcKay I'm assuming you're running `taskd` 1.1.0?

Yes, taskd 1.1.0 3caa8e2

**Comment by djmitche** [comment] 2021-12-11 21:51
How were you able to replicate this?  I have seen similar problems with 2.5.1 and 2.5.3 talking to the server.

**Comment by tbabej** [comment] 2021-12-16 05:30
I believe this problem is due to 2.6.x clients being incompatible with taskd 1.1.x server (while 1.2.x works fine, as far as this issue goes). Reproducers below:

First we need to kick off the server

```
$ git checkout 1.1.0
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo; make -j 8; sudo make install
$ taskd server --data ~/.taskd/
```

And then, in a different terminal:

```
$ task --version
2.6.1
$ export TASKDATA=/tmp/task1
$ mkdir $TASKDATA
$ task add test
TASKDATA override: /tmp/task1
Created task 1.
$ task add test2 dep:1
TASKDATA override: /tmp/task1
Created task 2.
$ task sync init
{"description":"test","entry":"20211216T052440Z","modified":"20211216T052440Z","project":"Inbox","status":"pending","type":"task","uuid":"2aa121cd-5276-4551-be8f-a7e3c47e8740"}
{"description":"test2","entry":"20211216T052444Z","modified":"20211216T052444Z","project":"Inbox","status":"pending","type":"task","uuid":"6138d62b-e286-4d0d-bc9b-8b71ec151b2a","depends":["2aa121cd-5276-4551-be8f-a7e3c47e8740"]}

TASKDATA override: /tmp/task1
Syncing with localhost:53589

Sync successful.  2 changes uploaded.
```

Now simulate the second client:

```
$ export TASKDATA=/tmp/task2
$ mkdir $TASKDATA
$ task sync

Syncing from string: {"description":"test","entry":"20211216T052440Z","modified":"20211216T052440Z","project":"Inbox","status":"pending","type":"task","uuid":"2aa121cd-5276-4551-be8f-a7e3c47e8740"}
Syncing from string: {"depends":"[\"2aa121cd-5276-4551-be8f-a7e3c47e8740\"]","description":"test2","entry":"20211216T052444Z","modified":"20211216T052444Z","project":"Inbox","status":"pending","type":"task","uuid":"6138d62b-e286-4d0d-bc9b-8b71ec151b2a"}
TASKDATA override: /tmp/task2
Syncing with localhost:53589
     add 2aa121cd-5276-4551-be8f-a7e3c47e8740 'test'
     add 6138d62b-e286-4d0d-bc9b-8b71ec151b2a 'test2'

Sync successful.  2 changes downloaded.
```

Note how the server response contains stringified list. This causes the pending.data to store invalid depends values:
```
$ cat /tmp/task2/pending.data 
[description:"test" entry:"1639632280" modified:"1639632280" project:"Inbox" status:"pending" type:"task" uuid:"2aa121cd-5276-4551-be8f-a7e3c47e8740"]
[dep_[\"2aa121cd-5276-4551-be8f-a7e3c47e8740\"]:"x" depends:"&open;\\\"2aa121cd-5276-4551-be8f-a7e3c47e8740\\\"&close;" description:"test2" entry:"1639632284" modified:"1639632284" project:"Inbox" status:"pending" type:"task" uuid:"6138d62b-e286-4d0d-bc9b-8b71ec151b2a"]
```

Current `1.2.0` branch of the `tasksever` repo works fine:
```
$ git checkout 1.2.0
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo; make -j 8; sudo make install
$ taskd server --data ~/.taskd/  # launch in a different terminal

$ task --version
2.6.1

# Simulate first client
$ export TASKDATA=/tmp/task1
$ task add test
TASKDATA override: /tmp/task1
Created task 1.
$ task add test2 dep:1
TASKDATA override: /tmp/task1
Created task 2.
$ task sync init
{"description":"test","entry":"20211216T050707Z","modified":"20211216T050707Z","project":"Inbox","status":"pending","type":"task","uuid":"2b00c1fe-5b81-44b9-bbce-f63e01a99205"}
{"description":"test2","entry":"20211216T050713Z","modified":"20211216T050713Z","project":"Inbox","status":"pending","type":"task","uuid":"313dddc9-9f25-450e-83a7-0d4cc1ec6dc3","depends":["2b00c1fe-5b81-44b9-bbce-f63e01a99205"]}

TASKDATA override: /tmp/task1
Syncing with localhost:53589

Sync successful.  2 changes uploaded.

# Simulate second client receiving the data
$ mkdir $TASKDATA
$ task all
TASKDATA override: /tmp/task2
No matches.

$ task sync

Syncing from string: {"description":"test","entry":"20211216T050707Z","modified":"20211216T050707Z","project":"Inbox","status":"pending","type":"task","uuid":"2b00c1fe-5b81-44b9-bbce-f63e01a99205"}
Syncing from string: {"depends":["2b00c1fe-5b81-44b9-bbce-f63e01a99205"],"description":"test2","entry":"20211216T050713Z","modified":"20211216T050713Z","project":"Inbox","status":"pending","type":"task","uuid":"313dddc9-9f25-450e-83a7-0d4cc1ec6dc3"}
TASKDATA override: /tmp/task2
Syncing with localhost:53589
     add 2b00c1fe-5b81-44b9-bbce-f63e01a99205 'test'
     add 313dddc9-9f25-450e-83a7-0d4cc1ec6dc3 'test2'

Sync successful.  2 changes downloaded.
````

We can note the sync string is not malformed in this case, als the pending.data contains correct data:


```
$ cat /tmp/task2/pending.data 
[description:"test" entry:"1639631227" modified:"1639631227" project:"Inbox" status:"pending" type:"task" uuid:"2b00c1fe-5b81-44b9-bbce-f63e01a99205"]
[dep_2b00c1fe-5b81-44b9-bbce-f63e01a99205:"x" depends:"2b00c1fe-5b81-44b9-bbce-f63e01a99205" description:"test2" entry:"1639631233" modified:"1639631233" project:"Inbox" status:"pending" type:"task" uuid:"313dddc9-9f25-450e-83a7-0d4cc1ec6dc3"]
```

I belive I already tracked down the reason this works in 1.2.0 / breaks in 1.1.0, but simply to fix this we'd need to release a new 1.2.0 taskd - and need to put proper integration tests in place to ensure compatibility going forward.

**Comment by mmeier86** [comment] 2021-12-22 13:36
@tbabej I don't think this is a client only problem, I've just observed some broken data on my taskd (also 1.1.0). I've tried syncing with the following client versions:

- 2.6.1
- 2.5.3
- 2.5.1

The original data was created by a 2.6.1 client.

Here is an example task, which shows the right dependencies in the `task info` output, but doesn't show as "blocked".
This task was originally created (and synced) by 2.5.1, but later modified and resynced with 2.6.1.

Most recent entry (closest to the bottom of the file) of the task in the **taskerver's** `tx.data` file:
```
{"description":"Nomad: Testen woher\/wie man denn jetzt template config files behandelt\/bekommt","entry":"20210612T155943Z","modified":"20211222T002910Z","priority":"M","project":"admin.cluster","reviewed":"20211010T105513Z","status":"pending","uuid":"d1ff0906-8c0c-4287-9241-c068038046c1","annotations":[{"entry":"20211221T140137Z","description":"Started task"},{"entry":"20211222T002910Z","description":"Stopped task"}],"tags":["admin","current","nomad"],"depends":["3d7e1cf3-fa6a-4930-967e-1177e8a0f1d6","7313b30f-f408-4a4d-919d-8ebd069f9fa3","e8f50472-ae73-4e2e-9968-930153487cb3"]}
```
Note especially how the "depends:" is an array of strings. This line was created by the sync of a change from yesterday, with a 2.6.1 client.
The following line is the same task, again from the `tx.data` file, but now from a sync on October 10th, before I switched to 2.6.1 (I'm afraid I'm not sure whether I was on 2.5.1 or 2.5.3 at the time):
```
{"depends":"e8f50472-ae73-4e2e-9968-930153487cb3,7313b30f-f408-4a4d-919d-8ebd069f9fa3","description":"Nomad: Testen woher\/wie man denn jetzt template config files behandelt\/bekommt","entry":"20210612T155943Z","modified":"20211010T105513Z","priority":"M","project":"admin.services.cluster","reviewed":"20211010T105513Z","status":"pending","tags":["admin","nomad","following"],"uuid":"d1ff0906-8c0c-4287-9241-c068038046c1"}
```
Note that now, the "depends" entry is just a comma separated string.

I've tried multiple fresh syncs (running `rm .task/*.data` before each) with all of the TW client versions mentioned above, they all showed the same behavior, not recognizing the task as being blocked. 
After sync with a 2.6.1 client, the same task from above looks like this in the `pending.data` file:
```
[annotation_1640095297:"Started task" annotation_1640132950:"Stopped task" dep_[\"3d7e1cf3-fa6a-4930-967e-1177e8a0f1d6\":"x" dep_\"7313b30f-f408-4a4d-919d-8ebd069f9fa3\":"x" dep_\"e8f504
     72-ae73-4e2e-9968-930153487cb3\"]:"x" depends:"&open;\\\"3d7e1cf3-fa6a-4930-967e-1177e8a0f1d6\\\",\\\"7313b30f-f408-4a4d-919d-8ebd069f9fa3\\\",\\\"e8f50472-ae73-4e2e-9968-930153487cb3\\\
     "&close;" description:"Nomad: Testen woher\/wie man denn jetzt template config files behandelt\/bekommt" entry:"1623513583" modified:"1640132950" priority:"M" project:"admin.cluster" rev
     iewed:"1633863313" status:"pending" tags:"admin,current,nomad" tags_admin:"x" tags_current:"x" tags_nomad:"x" uuid:"d1ff0906-8c0c-4287-9241-c068038046c1"]
```

**Comment by mowgli** [comment] 2021-12-22 13:51
Is there a way to fix the broken dependency entries in local *.data files? Edit: And would the change to taskd 1.2 fix all issues?

Some infos for questions above that I did not answer until now as the assumption behind got invalidated by other comments:
* Yes, I use self hosted taskd on a devuan system. Its version is 1.1.0. And there is no other version available at the distributions I use.
* The problem occurred when updating to task 2.6.x. But I cannot rule out that files got broken with earlier versions.
* At least at some time, I had a mix of 2.5.x clients on one machine and 2.6.x clients on the other.

**Comment by djmitche** [comment] 2021-12-22 14:22
I'm definitely seeing more of this lately, stuck somewhere between my multiple replicas.  I think it was harder to see before 2.6.1 because the invalid `depends` property was usually ignored, whereas now it's split into `dep_[\"...` properties, and those are incorrectly serialized, resulting in much more prevalent errors.

**Comment by djmitche** [comment] 2021-12-22 14:24
(sorry, I meant to actually answer the question!)

My fix has been to search for `dep_[`, `dep_"`, and `depends:"&open` in `.task/pending.data` and `.task/completed.data` and delete the relevant properties.  That said, doing so has not made the issue go away yet.

**Comment by djmitche** [comment] 2021-12-22 14:29
I'll try to chase this down soon.  Hopefully a "hack" can be applied to try to undo the incorrect form of the `depends` proeprty when it's uncovered, before it ends up causing incorrect serialization.

**Comment by tbabej** [comment] 2021-12-22 15:24
> And would the change to taskd 1.2 fix all issues?

As far as I can tell, this is fixed on 1.2.0 taskserver branch, at least it did so in my testing. There was a transition between 2.5.1 and 2.6.0 to treat `depends` attribute as an JSON array (previously `,` separated string), which is causing this as far as I can tell.

It would be nice if somebody could confirm taskd 1.2.0 HEAD fixes the issue for them.

**Comment by tbabej** [comment] 2021-12-22 15:25
@mmeier86 You're right, it's not a client only issue, in the sense that once the broken data is generated on the server, it will be propagated to clients of any version :slightly_smiling_face:

**Comment by djmitche** [comment] 2021-12-22 15:36
Ah, you're right -- I was able to reproduce this from a clean set of replicas, with just 2.6.1.

I don't want to upgrade freecinc to test, so ideally someone running their own server can test.  Once it's released I can upgrade freecinc :)

**Comment by mowgli** [comment] 2021-12-22 15:39
Well, how is the upgrade path to taskd 1.2? And when something break, is there a way back?

And what about the client side? Do I have to delete pending.data and completed.data?

**Comment by tbabej** [comment] 2021-12-22 15:47
Completely backing up client data is always an option, which I would definitely take in this case as a precaution. I would recommend trying to reproduce this with a completely new and empty `~/.task` directory (and clean server data), and if things work as expected, you can switch back to your original data and override the data on the server using `task sync init`.

**Comment by mowgli** [comment] 2021-12-22 15:50
You mean, `task sync init` with still empty data on the server?

**Comment by mowgli** [comment] 2021-12-22 15:50
And what is with multiple clients? Do I have to clear all clients before?

**Comment by tbabej** [comment] 2021-12-22 16:04
> You mean, `task sync init` with still empty data on the server?

This command will upload the current state of one client to the server, so it will technically "overwrite" what is currently on the server.

> And what is with multiple clients? Do I have to clear all clients before?

You will need at least two clients. I'd recommend starting from clean state on each.

**Comment by mowgli** [comment] 2021-12-22 16:35
Ok, tried that.

I do not know how to check on the server if the bug is gone but the client .data files (on the first client) still contain the broken entries.

**Comment by mowgli** [comment] 2021-12-22 16:45
… and if I remove all .data files from .task, I get `Unrecognized Taskwarrior file format or blank line in data.` with the following sync.

**Comment by mowgli** [comment] 2021-12-22 16:55
So, my impressions from taskd 1.2.0 from git is that I am not able anymore to sync a empty client. However, sync with undeleted data on client *and* server works as expected.

**Comment by bradyt** [comment] 2021-12-22 20:03
> … and if I remove all .data files from .task, I get Unrecognized Taskwarrior file format or blank line in data. with the following sync.

> So, my impressions from taskd 1.2.0 from git is that I am not able anymore to sync a empty client. However, sync with undeleted data on client and server works as expected.

This might be a small subtle issue, but maybe you can clarify how to reproduce that issue. I created the following plausible scenario:

```
> mkdir /tmp/test
> cd /tmp/test
> HOME=$(pwd)
> task
A configuration file could not be found in 

Would you like a sample /tmp/test/.taskrc created, so Taskwarrior can proceed? (yes/no)
> # yes
> echo '' > .task/pending.data
> task
[task next]
Unrecognized Taskwarrior file format or blank line in data. in /tmp/test/.task/pending.data at line 1
> echo -n '' > .task/pending.data
> task
[task next]
No matches.
```

I get a similar error if I try `task sync init`, I think because `init` means the `.task/backlog.data` is ignored and uses instead `completed.data` and `pending.data`.

If I'm purely testing, my habit is often to `rm .task/*.data`, but please be cautious in considering that.

I'm using task 2.5.3 and taskd 1.1.0.

**Comment by mmeier86** [comment] 2021-12-23 00:25
If anyone is interested in a quick fix, the following `sed` execution/shell script seems to do the trick for me:

```bash
sed -i\
  -e 's#\[\\"##g'\
  -e 's#\\"\]##g'\
  -e 's#\&open\;\\\\\\\"##g'\
  -e 's#\\\\\\\"##g'\
  -e 's#\&close\;##g'\
  -e 's#\\\"##g'\
  "$1"
```

Edit: To be executed on all three data files: `pending.data`, `undo.data` and `completed.data`.

**Comment by mowgli** [comment] 2021-12-23 05:55
> > … and if I remove all .data files from .task, I get Unrecognized Taskwarrior file format or blank line in data. with the following sync.
> 
> > So, my impressions from taskd 1.2.0 from git is that I am not able anymore to sync a empty client. However, sync with undeleted data on client and server works as expected.
> 
> This might be a small subtle issue, but maybe you can clarify how to reproduce that issue. I created the following plausible scenario:
> 
> ```
> > mkdir /tmp/test
> > cd /tmp/test
> > HOME=$(pwd)
> > task
> A configuration file could not be found in 

Well, this is still a productive setup with the server reachable over the internet. So I setup my own certificate, CA and credentials.

That would not allow to clean all. I can only clean the data files by removing them.

A subsequent `task sync` (without init) gives the mentioned error message. It is not a task report that triggers the error!

> Would you like a sample /tmp/test/.taskrc created, so Taskwarrior can proceed? (yes/no)

Well, as mentioned above, it includes the certificates. I also have tuned reports, colors and urgencies.

> > echo '' > .task/pending.data
> > task
> [task next]
> Unrecognized Taskwarrior file format or blank line in data. in /tmp/test/.task/pending.data at line 1
> > echo -n '' > .task/pending.data
> > task
> [task next]
> No matches.
> ```

Well, even without creating the data files, they get created with zero file size by task itself.

> If I'm purely testing, my habit is often to `rm .task/*.data`, but please be cautious in considering that.
> 
> I'm using task 2.5.3 and taskd 1.1.0.

Well, this is all about task 2.6.x and taskd 1.2.0. I never had that problems with your setup.

**Comment by bradyt** [comment] 2021-12-23 07:06
I still see the same behavior with task 2.6.1 (homebrew) and taskd 1.2.0 (at commit `7f41114`).

I came up with another (oversimplified) scenario, that might be a little closer to what you describe.

At server: 
```
cd $TASKDDATA/orgs/Public/users/$credentialsKey
echo '{' > tx.data
```

At client:

```
> rm .task/*.data
> task sync
Syncing with $server:53589

Sync failed.  The Taskserver returned error: 500 Unrecognized Taskwarrior file format or blank line in data. at line 0
```

Of course I doubt your `tx.data` file consisted of `{`, but maybe that's another idea that there was some error in the data there. Potentially you could cut the data in half recursively to narrow down the location of some syntax error, but I imagine that data has already been replaced.

**Comment by bradyt** [comment] 2021-12-23 07:14
Perhaps you can search the logs to see what line number caused the error, then check that line number in `tx.data`.

**Comment by mowgli** [comment] 2021-12-23 07:19
Well, I did the advice and rm tx.data completely, then `task sync init` then `rm .task/*.data` and then `task sync`, which led to the problem. So if tx.data gets corrupted, it is done by the sync.

**Comment by djmitche** [comment] 2021-12-23 14:11
The "Unrecognized Taskwarrior file format" error occurs for me, too, but is a _different_ issue from the one being discussed here.  In my experience, it's typically blank lines or lines with only `[]` at the beginning of one of the .task files.  If anyone can reproduce _creation_ of such a broken DB with `task` (not with `echo` 😄), that'd be a good new issue to file.

**Comment by mowgli** [comment] 2021-12-24 12:10
> The "Unrecognized Taskwarrior file format" error occurs for me, too, but is a _different_ issue from the one being discussed here. In my experience, it's typically blank lines or lines with only `[]` at the beginning of one of the .task files. If anyone can reproduce _creation_ of such a broken DB with `task` (not with `echo` smile), that'd be a good new issue to file.

I agree, it is a different bug. However, it makes the mentioned mitigation by upgrading taskd impossible.

As I wrote above, I only triggered the bug with `task` itself (well, deleting by `rm` included).

**Comment by mowgli** [comment] 2021-12-24 12:20
> If anyone is interested in a quick fix, the following `sed` execution/shell script seems to do the trick for me:
> 
> ```shell
> sed -i\
>   -e 's#\[\\"##g'\
>   -e 's#\\"\]##g'\
>   -e 's#\&open\;\\\\\\\"##g'\
>   -e 's#\\\\\\\"##g'\
>   -e 's#\&close\;##g'\
>   -e 's#\\\"##g'\
>   "$1"
> ```

Does not work if you have a description of kind `"blabla \"bla\" blabla"`, so, including a `"` in the description of a task.

**Comment by bradyt** [comment] 2022-01-16 06:57
Do I understand correctly, that current stable Taskwarrior, current stable Taskserver, and dependency feature, are not compatible right now? If there will be a reasonable delay on a new release for Taskserver, presumably it would be even more difficult to revert the breaking feature in Taskwarrior? Also, presumably bugs may surface in a new release of Taskserver, so it would be nice if we could get Taskwarrior 2.6.X working with Taskserver 1.1.0.

**Comment by bradyt** [comment] 2022-01-16 07:04
I'm going to delete the previous message (and this one), FYI, I'll try to understand the current state a bit more before commenting.

**Comment by djmitche** [comment] 2022-01-16 17:00
We could apply a quick fix to recognize this particular error (a `depends` property beginning and ending with `[..]`) and "undo" the damage from the task server.  That might be a good stopgap.

Note that this has been a latent bug for some time.  Changes in 2.6.1 to "split" the depends property into multiple properties just made it more apparent, where before the only effect was that dependency relationships sometimes weren't sync'd properly.

**Comment by tbabej** [comment] 2022-01-16 20:35
Indeed, this might be a good course of action, given that upgrading clients is generally easier than upgrading the server :slightly_smiling_face:

**Comment by djmitche** [comment] 2022-01-17 21:53
It looks like (a) I got the fix wrong for the multiple-dependency case and (b) this doesn't work for the single-dependency case, anyway.

**Closed as completed** 2022-01-20 00:34 UTC
Labels: type:bug
