### ISSUE TITLE
`project.not:side-quest or urgency>5` no longer working in 3.0.2 for context definition

### ISSUE THREAD

**Issue by adriangalilea** [GothenburgBitFactory/taskwarrior#3440] opened 2024-05-05 09:02 UTC
I had:
`context.default.read=project.not:side-quest or urgency>5`

For my default context, and  after upgrading to 3.0.2 (haven't tested 3.0.0/1) it no longer works, how can I use the urgency filter again?

I also tried:
`context.default.read="project.not:side-quest or urgency>5"`

And it did not work either

More testing:

`task list "project.not:side-quest or urgency>5"`
Does not work

but
`task list "urgency>5"`
and
`task list "project.not:side-quest"`

Work well when used in isolation.

Funniest thing is
`priority:H or +next or urgency>5`

This works perfectly fine, so I have no clue what's causing it not to work, is it `project.not` or a project with a `-` ?

**Comment by djmitche** [comment] 2024-05-06 01:03
ISTR projects can't have a `-` in them, as the command-line parser interprets that as subtraction. But #1537 suggests that was fixed 6 years ago.

Also, I can't reproduce this:
```
⸩ task list "project.not:side-quest or urgency>4"
Found existing '*.data' files in /home/dustin/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.

ID Age  P Project    Tags Description Urg 
 3 3min M            next bing        18.9
 2 4min M main-quest      bar          4.9
 1 4min M side-quest      foo          4.9

3 tasks
```

What does "no longer works" mean?

**Comment by adriangalilea** [comment] 2024-05-06 06:23
It doesn't work to me, it literally gives me a list of all the tasks, including below 4 urgency side-quest's

<img width="1433" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/3ad8d0dc-27a2-439c-8925-12b5951c3a7a">

it was working fine in 2.6 tho.

**Comment by djmitche** [comment] 2024-05-06 17:26
Hm, it looks like all of those tasks match `project.not:side-quest` The few at the bottom have a similar project, but it doesn't match exactly. Which of those would you expect to not see?

**Comment by adriangalilea** [comment] 2024-05-06 18:01
> Hm, it looks like all of those tasks match `project.not:side-quest` The few at the bottom have a similar project, but it doesn't match exactly. Which of those would you expect to not see?

The tasks at the bottom are from project `side-quest` so they should be excluded regardless of how you interpret the filter, no? I would understand if they showed up if they had urgency above 5 but is not the case.

I think my intention was something like  "show me all tasks with urgency above 5 unless it's from project side-quest" I would be fine if it interpreted it as "show me all tasks that are not from project side-quest unless they have urgency above 5" but neither seems to happen.

I'm positive it was working as expected in 2.6, do you want me to test it? I have a backup of my exported tasks, I can install it in a venv or something.

**Comment by djmitche** [comment] 2024-05-06 20:48
I think `project.not` is doing an exact match, and not with regard to subprojects. So `side-quest.e-id` is "not" `side-quest`. I could be wrong, though - I have not looked at the filtering or project code.

I don't think anything related to this changed in the 3.0 release. If you export from 3.0 and re-import the same in 2.6 (maybe just installed in a temporary VM or container), is the output different?

**Comment by djmitche** [comment] 2024-05-07 01:01
Huh, I am wrong:
```
✖ sofia ~/p/taskwarrior ⸨issue3429⸩
⸩ t
ID Age   Project Description Urg 
 1 23h   foo     foo            1
 2 23h   foo.bar foo            1

2 tasks
✖ sofia ~/p/taskwarrior ⸨issue3429⸩
⸩ t list project.not:foo
No matches.
✖ sofia ~/p/taskwarrior ⸨issue3429⸩
⸩ t list project.not:foo.bar

ID Age   Project Description Urg 
 1 23h   foo     foo            1

1 task
```

It looks like it's doing a prefix match, which is to say, `project.not:foo` says "`project` does not begin with `foo`"

That said, I can replicate what you are seeing even with 2.6.2:
```
✖ sofia ~                                                                                                                                                                                                                                                                                                                      
⸩ t 'project.not:side-quest or urgency>5'                                                                                                                                                                                                                                                                                      
...
88 side-quest M               21h    4.9 magnets
```
Task 88 has an urgency of 3.9. It does not appear in `task project.not:side-quest` nor `task "urgency>5"`.

To be honest, I have no idea how the filtering works in Taskwarrior, so I'm not sure how much more help I can be.

**Comment by adriangalilea** [comment] 2024-05-07 07:09
Ok, this is very odd,

I created this issue because my context wasn't working and when I tried using `task list` with the filter I replicated it not working.

Then I recreated my 2.6 and it worked just fine, but then I returned back to my machine and it's also working.

<img width="1438" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/ca36ba0e-cd4f-49af-a424-938ff9019eee">

As you can see no side-quest task in sight, however if I run, `task list "project.not:side-quest or urgency>5"` it doesn't filter and gives me the whole task list, so perhaps for whatever reason my context didn't work momentarily and when I tried to debug with `task list` or `task` it didn't work so I assumed it was a bug and didn't try further.

@djmitche Try the very same filter but in an actual context and tell me if it works for you as it works for me,

I'm not sure what's going on, wasn't the filter of the context supposed to work the same as when used on `task` or `task list`?

I gotta say, I'm quite a bit dyslexic and some of it may be my brain malfunctioning. So apologies for that and thank you so much for your help.

**Comment by djmitche** [comment] 2024-05-09 01:29
I don't know much about context, to be honest. Maybe there's something in how the filter supplied by the context is combined with the filter on the command line?

**Comment by adriangalilea** [comment] 2024-05-09 05:44
> I don't know much about context, to be honest. Maybe there's something in how the filter supplied by the context is combined with the filter on the command line?

No idea, but I thought context definition and `task list "..."` was supposed to work the same.

**Comment by djmitche** [comment] 2024-05-10 01:31
Me too :)

**Comment by adriangalilea** [comment] 2024-05-10 15:30
Some funny results:


This doesn't do anything:
```
❯ task "project.not:side-quest or urgency>5" list
```

This work perfectly:

```
❯ task project.not:side-quest or urgency\>5 list
```

```
❯ task list project.not:side-quest or urgency\>5
```


Fails:

```
❯ task list \(project.not:side-quest or tags.not:side-quest\) or urgency\>5
Mismatched parentheses in expression
```

Works:

```
task list "(project.not:side-quest and tags.not:side-quest)" or urgency\>5
```

Overall very inconsistent and hard to pick up, I think this needs better documentation and perhaps a re-work.

What do you think @djmitche 

I managed to make default context as I intended:
`context.default.read=(project.not:side-quest and tags.not:side-quest) or urgency>5`

Now I'll not see side-quest's either from projects under side-quest or specifically tagged side-quest tasks, unless they are urgent :)

**Comment by djmitche** [comment] 2024-05-14 01:43
I'm glad you got this sorted out for yourself!

That certainly looks like a parsing issue. I had always assumed that Taskwarrior kind of puts all of the command-line "words" back together separated by spaces, and then re-parses them. So, in 

```
❯ task "project.not:side-quest or urgency>5" list
```
it parses `project.not:side-quest or urgency>5` as a filter, and I would expect in
```
❯ task project.not:side-quest or urgency\>5 list
```
it gets the "words" `project.not:side-quest`, `or`, and `urgency>5` from the shell, joins them with spaces, and parses the exact same thing. But, it seems that's not the case.

I don't know if there's anyone around who understands the command-line parsing well enough to explain the difference..

**Comment by adriangalilea** [comment] 2024-05-14 14:28
> I don't know if there's anyone around who understands the command-line parsing well enough to explain the difference..

This worries me a bit, does it mean no one is supporting that part of the code anymore?

**Comment by ryneeverett** [comment] 2024-05-14 15:13
This seems like another zshell issue. Were any of the incorrect results reproducible on bash? I doubt there ever was full zshell support.

**Comment by djmitche** [comment] 2024-05-27 19:24
Closing on the assumption this was a zsh issue.

**Comment by adriangalilea** [comment] 2024-05-27 21:55
Sorry to reply late, I was quite busy.

> Closing on the assumption this was a zsh issue.

It probably is 👍 

> This seems like another zshell issue. Were any of the incorrect results reproducible on bash? I doubt there ever was full zshell support.

Where is this documented?
Shouldn't there be a warning somewhere about this?

**Comment by djmitche** [comment] 2024-05-27 22:06
I'm not sure - I don't know anything about zshell.

**Comment by adriangalilea** [comment] 2024-05-27 22:15
@djmitche I'm not sure how deep the lack of compatibility goes with zshell, if it's something generic, maybe it should be either on the getting started, config or install areas of the docs, some disclaimer stating this.

If it's something only related to filters, just there I guess.

@ryneeverett any idea?

**Comment by ryneeverett** [comment] 2024-05-29 01:57
For context, I've been an ignorant zshell user for about a decade now but sadly have not made any intentional effort to learn about it. So everything I think I know is derived from my own observations.

The biggest difference I've noticed from bash is that parameters are often parsed differently and zsh has more "special characters" which need to be quoted in order to be parsed as strings rather than zsh operators. My observation is that these issues seem to occur even with extremely popular and professionally maintained tools, so I would assume that these zsh quirks just need to be worked around by the end user and are not something the tool maintainers can always "fix".

So my thinking on potential shell compatibility issues such as this one are:

1. The first step is determining if it truly is a zshell issue by seeing if we can reproduce it on bash.
2. If it is in fact a zshell issue, it can probably be worked around with the right quoting/escaping.
3. If it is in fact a zshell issue, there's a good chance we cannot do anything to address it.
4. Even if we can do something to address it, it probably isn't a regression/bug so much as a feature (intentional zsh support) which we never had in the first place.


I recall Ed Matthia mentioning in the last community meeting that he whipped up a zsh script to fix something so he's probably more knowledgeable than me about this. Maybe he'd be willing to weigh in but I'm not sure if he has a github or what his handle is.

**Comment by djmitche** [comment] 2024-05-30 22:19
https://github.com/GothenburgBitFactory/taskwarrior/issues/3440#issuecomment-2109119812 was reproduced in bash.

**Comment by djmitche** [comment] 2024-11-24 21:34
Oh, TIL `rc.debug=1` shows a bunch of stuff about the parsing:
```
⸩ task rc.debug=1 'project.not:side-quest or urgency>5'
Timer Config::load (/home/dustin/p/taskwarrior/.taskrc) 0.000594 sec
No context set
Hook directory not readable: /home/dustin/p/taskwarrior/.task/hooks
Parse Tree (before command-specifіc processing)
  _original_args
    /home/dustin/p/taskwarrior/build/src/task next rc.debug=1 project.not:side-quest or urgency>5
  _args
    word basename='task' raw='/home/dustin/p/taskwarrior/build/src/task' BINARY 
    identifier canonical='next' raw='next' DEFAULT CMD READONLY SHOWSID RUNSGC USESCONTEXT ALLOWSFILTER 
    pair modifier='debug' name='rc' raw='rc.debug=1' separator='=' value='1' CONFIG ORIGINAL 
    op raw='(' ORIGINAL FILTER 
    pair canonical='project' modifier='not' name='project' raw='project.not:side-quest or urgency>5' separator=':' value='side-quest or urgency>5' QUOTED ORIGINAL FILTER 
    op raw=')' ORIGINAL FILTER 

No context set
Filtered 0 tasks --> 0 tasks [pending only]
Perf task 3.2.0 54a94bd18 20241124T212407Z init:2322 load:191 gc:12449 filter:1676 commit:0 sort:1 render:0 hooks:1 other:3325 total:19965

Configuration override rc.debug=1
No matches.

⸩ task rc.debug=1 project.not:side-quest or urgency\>5
Timer Config::load (/home/dustin/p/taskwarrior/.taskrc) 0.000426 sec
No context set
Hook directory not readable: /home/dustin/p/taskwarrior/.task/hooks
Parse Tree (before command-specifіc processing)
  _original_args
    /home/dustin/p/taskwarrior/build/src/task next rc.debug=1 project.not:side-quest or urgency>5
  _args
    word basename='task' raw='/home/dustin/p/taskwarrior/build/src/task' BINARY 
    identifier canonical='next' raw='next' DEFAULT CMD READONLY SHOWSID RUNSGC USESCONTEXT ALLOWSFILTER 
    pair modifier='debug' name='rc' raw='rc.debug=1' separator='=' value='1' CONFIG ORIGINAL 
    op raw='(' ORIGINAL FILTER 
    pair canonical='project' modifier='not' name='project' raw='project.not:side-quest' separator=':' value='side-quest' ORIGINAL FILTER 
    op raw='or' ORIGINAL FILTER 
    word raw='urgency>5' QUOTED ORIGINAL FILTER 
    op raw=')' ORIGINAL FILTER 

No context set
Filtered 1 tasks --> 0 tasks [all tasks]
Perf task 3.2.0 54a94bd18 20241124T212412Z init:14815 load:75 gc:3975 filter:904 commit:0 sort:1 render:0 hooks:1 other:4727 total:24498
```

And that clarifies how the parsing is done -- in the first (quoted) example, it is looking for tasks that do not have project 'side-quest or urgency>5' which would be a weird name for a project. In the second (`\>`) example, it parses as expected, with a project filter OR an urgency filter.

I suspect this one:
```
task list "(project.not:side-quest and tags.not:side-quest)" or urgency\>5
```
works because Taskwarrior sees the `(` and figures it's an expression it needs to evaluate, and rc.debug=1 indicates that's correct. So, this isn't a shell issue at all, but my misunderstanding of how parsing works. This was incorrect in my May 13 comment:

> I had always assumed that Taskwarrior kind of puts all of the command-line "words" back together separated by spaces, and then re-parses them. 

So that means when the context is added:
```
Parse Tree (before command-specifіc processing)
  _original_args
    /home/dustin/p/taskwarrior/build/src/task ( project.not:side-quest or urgency > 5 ) next rc.debug=1
  _args
    word basename='task' raw='/home/dustin/p/taskwarrior/build/src/task' BINARY 
    op raw='(' QUOTED FILTER 
    pair canonical='project' modifier='not' name='project' raw='project.not:side-quest' separator=':' value='side-quest' FILTER 
    op raw='or' FILTER 
    dom raw='urgency' FILTER 
    op raw='>' QUOTED FILTER 
    number raw='5' FILTER 
    op raw=')' QUOTED FILTER 
    identifier canonical='next' raw='next' CMD READONLY SHOWSID RUNSGC USESCONTEXT ALLOWSFILTER 
    pair modifier='debug' name='rc' raw='rc.debug=1' separator='=' value='1' CONFIG ORIGINAL 
```
It's not shown in the text pasted above, but the `( project ... > 5)` in `_original_args` is colored differently. So I'd guess that Taskwarrior is taking the context value, parsing it into words somehow (breaking on space, maybe allowing `"` and/or `\`?), and inserting those words nested in `( .. )` into the command line as if they had come from the shell.

I think the original issue was solved here, and this is just a further understanding of what's going on.

**Closed as completed by djmitche** 2024-11-24 21:34 UTC
Labels: type:bug, topic:command-line
