### ISSUE TITLE
Task commands blocks and tasks 100% cpu when running as a subprocess.

### ISSUE THREAD

**Issue by cmal** [GothenburgBitFactory/taskwarrior#2175] opened 2019-05-31 13:33 UTC
#### To report a bug...

* What command(s) did you run? task 1 info
* What did you expect to happen?  run
* What actually happened? blocks and takes 100% cpu
* Paste the output of the ```task diag``` command.
task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Oct 20 2018 08:11:44
      CMake: 3.12.1
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.10
 Build type: Release

Configuration
       File: /Users/xxx/.taskrc (found), 2434 bytes, mode 100644
       Data: /Users/xxx/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 39.98.70.118:53589
         CA: /Users/xxx/.task/ca.cert.pem, readable, 3700 bytes
      Trust: strict
Certificate: /Users/xxx/.task/client.cert.pem, readable, 3674 bytes
        Key: /Users/xxx/.task/client.key.pem, readable, 25367 bytes
    Ciphers: NORMAL
      Creds: xxx/xxx/************************************

Hooks
     System: Enabled
   Location: /Users/xxx/.task/hooks
             (-none-)

Tests
      $TERM: dumb (0x0)
       Dups: Scanned 4 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 4 tasks for broken references:
             No broken references found

`task x info`, `task ghistory` commands will take 100% cpu and block forever when using inside emacs's `shell mode`, `eshell`,  or whenever a subprocess is created for it.

Btw the `task x info` will not always block forever. In my current task list, one of the tasks will not block. The difference for this task is its title is utf8, and this task returns fewer fields.

**Comment by pbeckingham** [comment] 2019-08-11 18:38
Could you paste the offending task here?  Take your pending.data file and cut it down to one line, and just cat the file and paste here.  I haven't seen this utf8 bug before.

**Comment by tbabej** [comment] 2021-01-25 03:52
This is possibly a duplicate of #2389, but we cannot be certain unless more information is provided. Closing for now, please reopen if the issue still occurs on 2.5.3 :slightly_smiling_face:

**Closed by tbabej** 2021-01-25 03:52 UTC
Labels: awaiting response, bug
