### ISSUE TITLE
[TW-1311] Indent continued annotation lines 

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1343] opened 2018-02-14 05:17 UTC
_Peter Vitt on 2014-05-02T09:30:52Z says:_ 

 When I print a task list (via next or list or long or ...), the list contains the annotations. Some of my annotations are longer than line length, so they get wrapped. But the additional lines do neither start at the indentation level of the annotation date nor one indentation level deeper, but at the start or the description column.

I think it would improve readability, if the wrapped lines are also indented, at least along with the date, better one level deeper.

**Comment by taskwarrior** [comment] 2018-02-14 05:18
Migrated metadata:
```
Created: 2014-05-02T09:30:52Z
Modified: 2017-02-01T12:53:41Z
```

**Comment by taskwarrior** [comment] 2018-02-14 05:18
_Paul Beckingham on 2014-05-02T19:18:44Z says:_ 

 The current behavior was intentional.  But what you are suggesting is much nicer.  Thank you!

**Comment by taskwarrior** [comment] 2018-02-14 05:18
_Peter Vitt on 2017-02-01T09:16:38Z says:_ 

 This seems to be the same issue, which I overlooked back then.

**Comment by taskwarrior** [comment] 2018-02-14 05:18
_Paul Beckingham on 2017-02-01T12:53:41Z says:_ 

 Thanks for linking the issues.

**Comment by tbabej** [comment] 2021-04-04 18:36
As above comments mention, this is a duplicate of #314, closing to unify discussions.

**Closed by tbabej** 2021-04-04 18:36 UTC
Labels: enhancement
