### ISSUE TITLE
`task ready` shows empty Due date column

### ISSUE THREAD

**Issue by steadmon** [GothenburgBitFactory/taskwarrior#2881] opened 2022-07-12 21:21 UTC
* What command(s) did you run?

`task ready`

* What did you expect to happen?

The "Due" column should show the due date for tasks with a due date. I've verified that the tasks have a due date that is visible with `task next`.
  
* What actually happened?

The "Due" column was displayed, but it was empty even for tasks with a due date.

* Paste the output of the ```task diag``` command.

```
task 2.6.2
   Platform: Linux

Compiler
    Version: 11.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.22.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.3
 Build type: Release

Configuration
       File: <HOME>/.config/task/taskrc (found), 1216 bytes, mode 100640
       Data: <HOME>/.local/share/task (found), dir, mode 40750
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: <HOME>/.config/task/hooks
             (-none-)

Tests
   Terminal: 237x124
       Dups: Scanned 30 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 30 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment] 2022-07-24 16:45
Interesting report. On a cursory glance, I can see at least one task in my `ready` report with displayed due date, so we'll need more info here to fix and reproduce :slightly_smiling_face: 

Can we see the definition of your `task show report.ready` and the `task export` (perhaps with censored description/other fields) of the offending task?

**Comment by steadmon** [comment] 2022-07-27 22:27
Sure:

```
$ task show report.ready

Config Variable          Value                                                                                                                                               
report.ready.columns     id,start.age,entry.age,depends.indicator,priority,project,tags,recur.indicator,scheduled.countdown,due.countdown,until.remaining,description,urgency
report.ready.context     1
report.ready.description Most urgent actionable tasks                                                                                                                        
report.ready.filter      +READY
report.ready.labels      ID,Active,Age,D,P,Project,Tags,R,S,Due,Until,Description,Urg                                                                                        
report.ready.sort        start-,urgency-
```

```
$ task 1,28 export
[
{"id":1,"description":"Wrap up release document","due":"20220616T070000Z","entry":"20220609T203916Z","modified":"20220614T175857Z","priority":"H","project":"release-docs","status":"pending","uuid":"55acdf90-ebbf-4b9c-99d7-7b099c348d5c","tags":["<redacted>"],"urgency":20.063},
{"id":28,"description":"Make travel plans for <redacted>","due":"20220727T070000Z","entry":"20220722T231441Z","modified":"20220722T231451Z","priority":"H","status":"pending","uuid":"378f2fd1-59f2-40a5-a4f0-0418ee72310f","urgency":15.1158}
]

**Comment by steadmon** [comment] 2022-07-27 22:29
Just realized that all my tasks due dates are overdue. When I add a due date for tomorrow, it shows up as expected in `task ready`. I still think it's an error to filter out overdue dates though.

**Comment by totallyuniquelily** [comment] 2024-01-21 19:27
I've also noticed: if an overdue task is the only ready task with a due date, `task ready` will still display the Due *column* even though it is empty in the report.
(So even if filtering out overdue dates were intended, the behavior still seems wrong)

**Comment by jadhachem** [comment] 2024-11-24 08:55
I see this issue too on v2.6.2. As far as I can tell, the general behavior is that columns of *countdown dates* are only rendered when at least one task has reached its countdown (whereas the expectation as I understand it is that it should be rendered when at least one task still has a positive countdown).

I suspect (but have not verified) that this was fixed in later versions in [this pull request](https://github.com/GothenburgBitFactory/taskwarrior/pull/2780).

---

To reproduce: Say we have a task due soon. `task ready` (configured with a `due.countdown` column) should display a countdown to its due date.
```
$ task add Due due:tomorrow
Created task 1.
$ task ready

ID Age  Description Urg
 1 1s   Due         8.35

1 task
```
The column doesn't show despite task 1 having a positive countdown.

Now if we include an overdue task (whose countdown would be empty):
```
$ task add Overdue due:yesterday
Created task 2.
$ task ready

ID Age   Due  Description Urg
 2  2s        Overdue     9.27
 1 21s   13h   Due         8.35

2 tasks
```
The column appears as expected.

For completeness, let's remove task 1.
```
$ task 1 done
Completed task 1 'Due'.
Completed 1 task.
You have more urgent tasks.
$ task ready

ID Age   Due  Description Urg
 1 17s        Overdue     9.27

1 task
```
The column is still there despite being empty.

A similar behavior occurs with `scheduled.countdown` (e.g. with the `list` report):
```
$ task add Future scheduled:tomorrow
Created task 2.
$ task list

ID Age  Description Urg
 1 1s   Future         0

1 task
$ task add Past scheduled:yesterday
Created task 2.
$ task list

ID Age  Sch  Description Urg
 2 1s        Past           5
 1 8s   13h   Future         0

2 tasks
```

**Comment by djmitche** [comment] 2024-11-24 13:27
I tested this with the latest release and the behavior is fixed. Thanks for the good reproduction recipe!

**Closed as completed by djmitche** 2024-11-24 13:27 UTC
