### ISSUE TITLE
Too long words messing up with the display of reports

### ISSUE THREAD

**Issue by a10dix** [GothenburgBitFactory/taskwarrior#2148] opened 2019-04-19 12:56 UTC
###### Clearly state the use case.
* What command did you run?
task add "https://www.google.com/search?client=firefox-b-d&ei=Ba65XNaoJMrSa7PJo4gK&q=very+long+url+example&oq=very+long+url+example&gs_l=psy-ab.3..0i19j0i22i30i19.5798.7265..7464...0.0..0.64.435.8......0....1..gws-wiz.......0i71.Pz7m21XJysw"
And then:
task list
* What actually happened?
The report has a minimum width of 277 and does not fit in the available width of 110.
I didn't know what I did to mess up with the display… I just had a messy display after I added many tasks over half a day. I understood the warning but:
— Where was the problem: my terminal, taskwarrior, me? And if me, where was my error in my 200 tasks?
— So what? What could I do to solve that?
* What did you expect to happen?
I expected a more precise warning message: “In this task, the description is too long” or something like that, so I would know where is the problem and have a suggestion about how to solve it, even I don't like it.

###### Clearly describe the feature.
* What do you suggest?
In the description field, at display/report time:
— Either URL may be parsed, and split anywhere;
— Or words lengths may be measured, and if too long, a warning may be issued with the report: “The word … in task … is too long to be displayed in this report in this window, and is getting the display messy. Do something!”.
— Or, what I prefer, words lengths are measured and too long words are cut without warning.

**Comment by pbeckingham** [comment] 2019-05-27 16:07
Looks like hyphenation is not working.

**Comment by tbabej** [comment] 2021-06-27 08:22
I believe this is a duplicate of #2023, which is fixed on 2.5.3 and 2.6.0

**Closed by tbabej** 2021-06-27 08:22 UTC
Labels: bug
