### ISSUE TITLE
[TW-1751] Add additional type of recurrance

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1775] opened 2018-02-14 17:22 UTC
_Jeffrey Ratcliffe on 2016-01-03T23:24:54Z says:_ 

 At the moment, it seems that new recurring tasks are created whether the previous task was completed or not.

However, some tasks, rather than being done always, say, on a Monday morning at 8:00, should be done 7 days after the previous one was completed.

Can this be achieved currently?

**Comment by taskwarrior** [comment] 2018-02-14 17:23
Migrated metadata:
```
Created: 2016-01-03T23:24:54Z
Modified: 2016-04-29T06:30:19Z
```

**Comment by taskwarrior** [comment] 2018-02-14 17:23
_Paul Beckingham on 2016-01-04T18:37:47Z says:_ 

 Not currently supported.

But this is something we'll be doing in 2.6.0, when we reimagine recurring tasks to do this and other requested behaviors.

**Comment by taskwarrior** [comment] 2018-02-14 17:23
_Scott Kostyshak on 2016-04-29T06:30:19Z says:_ 

 This and 1774 seem to be duplicates to me.

**Comment by jcrben** [comment] 2018-06-16 20:38
It seems like https://github.com/JensErat/task-relative-recur could help with this

**Comment by jcrben** [comment] 2018-06-16 20:42
Closing as duplicate of https://github.com/GothenburgBitFactory/taskwarrior/issues/203

**Closed by jcrben** 2018-06-16 20:42 UTC
Labels: enhancement, recurrence

**Comment by proedie** [comment] 2021-03-25 17:00
Is this still planned to be in TW 2.6?

**Comment by tbabej** [comment] 2021-03-26 06:44
Hi @proedie, yes, this is still part of the [planned recurrence overhaul](https://taskwarrior.org/docs/design/recurrence.html) for 2.6.0.

**Comment by proedie** [comment] 2021-03-26 14:16
Excelent, thank you @tbabej. (And sorry for accidently commenting in this issue instead of 203.)
