### ISSUE TITLE
[TW-26] Lost data when syncing with a full disk

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#88] opened 2018-02-12 14:56 UTC
_Bret Comnes on 2012-09-17T23:33:32Z says:_ 

 [Issue rewritten to eliminate obsolete references]

Sync can lose data when merging in tasks from the server, if the local disk is full.

This should instead write to a temporary file such that data is not lost, a proper error message should be generated, and a subsequent sync with sufficient local space should succeed as though nothing went wrong.

**Comment by taskwarrior** [comment] 2018-02-12 14:57
Migrated metadata:
```
Created: 2012-09-17T23:33:32Z
Modified: 2017-01-16T15:06:26Z
```

**Comment by vrusinov** [comment] 2021-07-05 22:44
Dupe of #1420?

This issue is older but #1420 has some discussion already so probably better to keep that one open.

**Closed** 2022-05-20 07:03 UTC
Labels: type:bug
