### ISSUE TITLE
Jira issues imported into GitHub bug tracker have wrong ticket numbers

### ISSUE THREAD

**Issue by sampablokuper** [GothenburgBitFactory/taskwarrior#2088] opened 2018-12-15 00:33 UTC
IIUC, around 14 February 2018, the TaskWarrior maintainers migrated the contents of TaskWarrior's previous bug tracker (a [Jira instance hosted free of charge by Atlassian](https://taskwarrior.org/news/news.20140303.html)) into the present GitHub bug tracker.

Unfortunately, there was some data loss/breakage in the process. For example:

- Tickets and comments that were imported from Jira into GitHub are shown as having been authored by @taskwarrior , preventing GitHub's [author searching](https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-author) from being able to identify the actual author.
- The Jira ticket numbers ["TW-XXX"] do not match the GitHub ticket numbers.
- Some Jira tickets seem to be missing entirely from the GitHub bug tracker.

I want to focus, here, on the second issue. At least two problems result from it:

- Broken links between issues. For example, ticket [TW-1138] (GitHub issue [#1173](https://github.com/GothenburgBitFactory/taskwarrior/issues/1173)) has links that now resolve to the wrong target. Specifically:
    - [this comment](https://github.com/GothenburgBitFactory/taskwarrior/issues/1173#issuecomment-365456283) has what would presumably have been, in a previous task tracker (possibly pre-dating Jira; but hopefully in Jira, too), a link to [TW-305], but that now resolves instead to [TW-263] (GitHub issue [#305](https://github.com/GothenburgBitFactory/taskwarrior/issues/305)).
    - [this comment](https://github.com/GothenburgBitFactory/taskwarrior/issues/1173#issuecomment-365456459) has what would presumably have been, in a previous task tracker, a link to [TW-169], but that now resolves to [TW-112] (GitHub issue [#169](https://github.com/GothenburgBitFactory/taskwarrior/issues/169)).

- Difficulty finding issues. This is a double whammy. For example, suppose I want to find [TW-10]:
    - If the Jira and GitHub ticket numbers matched, this would be easy: I would simply go to [`https://github.com/GothenburgBitFactory/taskwarrior/issues/10`](https://github.com/GothenburgBitFactory/taskwarrior/issues/10). But because they don't, I have to search. That's the first whammy: having to search, instead of just being able to type in the URL.
    - The second whammy is that due to [a GitHub bug](https://stackoverflow.com/questions/26433561/how-to-search-on-github-to-get-exact-matches-like-what-quotes-do-for-google), there is no way within GitHub to avoid irrelevant search results, i.e. even if I search for [`is:issue in:title "TW-10"`](https://github.com/GothenburgBitFactory/taskwarrior/issues?utf8=%E2%9C%93&q=is%3Aissue+in%3Atitle+%22TW-10%22), I will get results like "[TW-1733] taskwarrior 2.5.0 can not compile FreeBSD 10.1", because they have a "TW" and a "10" in the title.

Does the TaskWarrior team plan to address these usability issues with the current GitHub bug tracker (e.g. by using their administrative access to move content imported from Jira to the correct GitHub ticket numbers)?

**Comment by JonasDralle** [comment] 2018-12-19 07:48
agreed.
The TW issue tracker is in broken state and only the maintainers can fix this

**Comment by mrossinek** [comment] 2018-12-30 14:07
I took the time to dig a little into this and created a list of all Github IDs (issues and pull requests). From this I was able to extract all those IDs from the migration that are missing (completing the list from #2087) [following the assumption that neither EX-70 nor TW-1954 ever existed]. I have summarized the statistics in the txt file below.

I have also added the list of all Github IDs if somebody has the time to construct a matrix which would match all EX or TW IDs to the corresponding Github IDs. This would allow to correct the referencing links (still manually though)...

I do not know if it is possible to correct the authors of the issues/comments.

[stats.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/2717203/stats.txt)
[list.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/2717204/list.txt)

Duplicate of #2087 (since this seems to be the more promising thread for discussions)

**Comment by tbabej** [comment] 2019-01-02 20:46
It is not possible to "correct" authors of issues or comments, as we do not have the permission to post in a different user's name. Orignal names are preserved in the bodies of the comments.

As far as cross-referencing `TW-XXXX` with a github issue, I encountered this multiple times today, and really, a fast "TW-XXXX github" search engine query solves this in couple of seconds.

**Comment by sampablokuper** [comment] 2019-02-07 20:18
@tbabej wrote:
> It is not possible to "correct" authors of issues or comments, as we do not have the permission to post in a different user's name.

I understand that. It's a flaw in GitHub. But as long as GBF is using GitHub for Taskwarrior's bug tracker, it's a flaw in Taskwarrior's bug tracker :(

A potential solution would be to migrate to a self-hosted (perhaps internal, i.e. not publicly-accessible) GitLab instance, which would let you fix these flaws; and then to migrate from that to a public GitLab instance, either self-hosted or hosted by gitlab.com . I am not 100% certain, but I *think* this would solve the problem.

> Orignal names are preserved in the bodies of the comments.

Yes, but these are not separately queryable in GitHub's faceted search.

> As far as cross-referencing TW-XXXX with a github issue, I encountered this multiple times today, and really, a fast "TW-XXXX github" search engine query solves this in couple of seconds.

That workaround is only successful for users who think to perform it. Unfortunately, anyone who is not aware of [this bug](https://github.com/GothenburgBitFactory/taskwarrior/issues/2088), i.e. probably most people browsing this bug tracker, will however almost certainly not think to perform that workaround :(

**Comment by tbabej** [comment] 2019-02-07 21:21
@sampablokuper It would solve the problem. It would also create the problem of everybody wanting to contribute (or everybody that has contributed in the past) having to create a new user account on that GitLab instance. Not sure that's better.

We have moved away from self-hosted JIRA to decrease the maintenance load on the core team. Unless somebody is willing to perform the migration and maintain the system long term and give a convincing case that doing so will increase, not decrease contribution rate, this is not something that is likely to happen. Not that I am opposed to it, mind you, just trying to set expectations right here.

**Comment by pbeckingham** [comment] 2019-02-07 21:32
The issues do not have the wrong numbers, they have different numbers.  User names have been captured where possible, and will be corrected iff someone wants to donate the time.  Are you, @sampablokuper volunteering the time to complete this task?

This is peripheral to the main effort, and we have worked very hard to eliminate all peripheral activity, because we can't support it either through donations or volunteered time.  From documentation patches, to bug triage, to bug fixing, there are simply zero volunteers putting in time and effort.  We have not even had the volunteers available to release v2.5.2, which was ready a year ago.

Any time I have is going towards bug fixes and planned work.

**Closed by pbeckingham** 2019-02-07 21:32 UTC
