### ISSUE TITLE
taskwarrior 2.5.3 time based filtering regression

### ISSUE THREAD

**Issue by cherusk** [GothenburgBitFactory/taskwarrior#2530] opened 2021-07-09 07:13 UTC
#### To report a bug...

* What command(s) did you run?

E.g. normalized example:

task wait.before:1w waiting

* What did you expect to happen?

To get shown only tasks the wait period of which ends in ~ 1week.

* What actually happened?

Getting shown all tasks in the project. The period specification(1w) is parsed and recognized according to taskwarrior debug output, but not interpreted then by the engine it appears.

* Paste the output of the ```task diag``` command.
Affected version 2.5.3

**Comment by cherusk** [comment] 2021-07-09 07:14
This is very well working on 2.5.1 still. I have "back-graded", but definitly something to be addressed as it's the upgrading path for a core feature.

**Comment by tbabej** [comment] 2021-07-09 11:20
Interesting, I can reproduce a problem here, but the outcome does not seem to be equivalent to what you're seeing. In particular, I don't get all tasks listed if I perform the following sequence of commands:

```
[warrior@tw-v2.5.3 ~]$ task add wait:1w this should show up
Created task 1.
[warrior@tw-v2.5.3 ~]$ task add this should NOT show up
Created task 2.
[warrior@tw-v2.5.3 ~]$ task wait.before:1w all
No matches.
[warrior@tw-v2.5.3 ~]$ task all

ID St UUID     Age   Wait Description            
 2 P  f6216e0a 22s        this should NOT show up
 1 W  873dab13 40s   6d   this should show up    

2 tasks
```

**Comment by tbabej** [comment] 2021-07-09 11:24
Looks like this is already fixed on 2.6.0, so hopefully the next upcoming release should address this for you :slightly_smiling_face:

```
[warrior@tw-2.6.0 ~]$ task add wait:1w this should show up
Created task 1.
[warrior@tw-2.6.0 ~]$ task add this should NOT show up
Created task 2.
[warrior@tw-2.6.0 ~]$ task wait.before:1w all

ID St UUID     Age   Wait Description        
 1 W  73ad5b1c 13s   6d   this should show up

1 task
```

 I'm gonna keep this issue open to make sure we add a regression test into the test suite.

**Comment by cherusk** [comment] 2021-07-09 14:10
Thanks :handshake:

**Comment by tbabej** [comment] 2021-07-10 13:39
Regression test implemented, thanks @cherusk for reporting!

**Closed** 2021-07-10 13:39 UTC
Labels: bug, reproduced
