### ISSUE TITLE
Sync reminder appears even when no sync server is specified / wanted (3.0.0)

### ISSUE THREAD

**Issue by 534nH** [GothenburgBitFactory/taskwarrior#3300] opened 2024-03-27 16:09 UTC
I don't have a need to sync taskwarrior to a server. Since upgrading to 3.0.0, I receive the message, "There are [##] local changes.  Sync required." every time I try to view tasks. There doesn't seem to be a way to turn this warning off.

**Comment by ryneeverett** [comment] 2024-03-27 16:12
Duplicate of #3297.

**Closed as completed** 2024-03-27 22:43 UTC
