### ISSUE TITLE
Compilation failed on WSL (windows 10)

### ISSUE THREAD

**Issue by stampf** [GothenburgBitFactory/taskwarrior#3378] opened 2024-04-19 17:17 UTC
#### To report a bug...

* What command(s) did you run?
** cmake -DCMAKE_BUILD_TYPE=release .
* What did you expect to happen?
** compilation ?
(I have the necessary tools as it seems in the non-error messages before the ones below).

* What actually happened?
Following error:
```
-- Using Corrosion as a subdirectory
error: failed to load manifest for workspace member `/home/nicolas/task-3.0.0/taskchampion/integration-tests`

Caused by:
  failed to read `/home/nicolas/task-3.0.0/taskchampion/integration-tests/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
CMake Error at _deps/corrosion-src/cmake/CorrosionGenerator.cmake:24 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 101"

Call Stack (most recent call first):
  _deps/corrosion-src/cmake/CorrosionGenerator.cmake:217 (_cargo_metadata)
  _deps/corrosion-src/cmake/Corrosion.cmake:1098 (_generator_add_cargo_targets)
  src/tc/CMakeLists.txt:11 (corrosion_import_crate)


-- Configuring incomplete, errors occurred!
```

**Comment by djmitche** [comment] 2024-04-19 23:44
I think this is a dupe of #3294. I should have a 3.0.1 out this weekend that fixes the issue. In the interim, if you remove the line containing `integration-tests` from `Cargo.toml` that should fix it.

**Closed as completed by djmitche** 2024-04-19 23:44 UTC

**Comment by AnabasisXu** [comment] 2025-01-13 06:59
I encountered a similar problem on Cygwin, despite the fact that `Cargo.toml` does exist:

```
-- Using Corrosion as a subdirectory
error: manifest path `/cygdrive/d/HOME/.emacs.d/test/task-3.3.0/Cargo.toml` does not exist
CMake Error at src/taskchampion-cpp/corrosion/cmake/CorrosionGenerator.cmake:26 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 101"

Call Stack (most recent call first):
  src/taskchampion-cpp/corrosion/cmake/CorrosionGenerator.cmake:227 (_cargo_metadata)
  src/taskchampion-cpp/corrosion/cmake/Corrosion.cmake:1113 (_generator_add_cargo_targets)
  src/taskchampion-cpp/CMakeLists.txt:19 (corrosion_import_crate)
```

**Comment by djmitche** [comment] 2025-01-13 13:31
I think that is a different error, so I have filed #3756.
