### ISSUE TITLE
Allow upper-case days of the week?

### ISSUE THREAD

**Issue by scottkosty** [GothenburgBitFactory/taskwarrior#2160] opened 2019-05-02 02:30 UTC
#### To report a bug...

* What command(s) did you run?

```
task due:Monday
```

* What did you expect to happen?

The same as the lower-case variant:

```
task due:monday
```

* What actually happened?

I received the following error:
```
'Monday' is not a valid date in the 'Y-M-D' format.
```

I tried to bisect to see where the change of behavior started occurring and ended up at 434e95f5. I haven't been following development closely, so I wouldn't be surprised at all if this change of behavior is desired/necessary. In that case, please close this issue and sorry for the noise. I did scan the change log and looked at https://taskwarrior.org/docs/dates.html but couldn't find information related to this change.

Edit: I should add that I don't mind this change much. It will be easy to get used to. I just want to make sure it was intended.

**Comment by mrossinek** [comment] 2020-12-12 17:38
It looks to me like this is an upstream issue in https://github.com/GothenburgBitFactory/libshared. I don't know that code at all but a quick skim through it and a short test suggests that the logic [here](https://github.com/GothenburgBitFactory/libshared/blob/master/src/Pig.cpp#L112) is too strict. As far as I can tell, the `reference` always only contains lower-case letters but in order to support also capitalized day and month names, the second argument should be converted to lower case.

I will suggest this change in a PR over there and link to this issue.

Tagging @tbabej who opened #2364 (a duplicate of this)

**Comment by vrusinov** [comment] 2021-05-29 15:47
I believe https://github.com/GothenburgBitFactory/taskwarrior/pull/2487 fixed.

Let's close this issue? (I don't believe I can).

**Comment by tbabej** [comment] 2021-05-29 15:49
Yes, this is correct. Support for capitalized days of the week / months is available on the dev branch and will be part of the next release.

**Closed by tbabej** 2021-05-29 15:49 UTC
Labels: enhancement

**Comment by tbabej** [comment] 2021-09-25 22:09
This was a regression in 2.5.2.
