### ISSUE TITLE
[TW-1774] recurring tasks with flexible wait/due dates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1798] opened 2018-02-14 17:58 UTC
_Allen J on 2016-02-21T21:29:16Z says:_ 

 [Paul Beckingham linked to some existing issues regarding recurrence, however they weren't quite how I imagine the problem and solution to be, so I am creating a new issue. There is one somewhat similar feature request, which people showed interest in, but it is from 2010. So it is perhaps time to reassess this situation.]

Let's say I have a recurring task like "give medicine to cat" that recurs every 30 days, with wait set to "due-1days".

So the task instances might be due Feb 13, March 14, April, 13, etc

But the important thing is the next instance should be due 30 days after the COMPLETION of the previous instance. For example, let's say I forget to do my task (or cannot do it) and instead of doing it on Feb 13, I do it on Feb 23.

Now the next instance is due March 14, but that is too soon because the medicine has to be given 30 days after the last time it was given. So the real due date should be Feb 23 + 30 days.

These kinds of tasks come up a lot. You should do them every X days, but if you forget and do it late, the next instance should be the current instance's completion date + X days, so it should be flexible.

The other thing is that new instances shouldn't be created automatically even when the user is inactive, but should be one new instance per one completed instance. Like if I have a task "take medicine" which recurs daily, if I forget a few days I should not have 4 instances of the same task, which is obviously wrong. There should just be one instance, notifying the user to take the medicine 1 time, not 4 times at once.

**Comment by taskwarrior** [comment] 2018-02-14 17:58
Migrated metadata:
```
Created: 2016-02-21T21:29:16Z
Modified: 2016-04-29T06:30:37Z
```

**Comment by taskwarrior** [comment] 2018-02-14 17:58
_Scott Kostyshak on 2016-04-29T06:30:37Z says:_ 

 This and 1751 seem to be duplicates to me.

**Comment by jcrben** [comment] 2018-06-16 20:36
It seems like https://github.com/JensErat/task-relative-recur could help here

**Comment by jcrben** [comment] 2018-06-16 20:41
Closing as duplicate of https://github.com/GothenburgBitFactory/taskwarrior/issues/203

**Closed by jcrben** 2018-06-16 20:41 UTC
Labels: enhancement, recurrence
