### ISSUE TITLE
Task crashes with ' Assertion '__pos <= size()' failed.'

### ISSUE THREAD

**Issue by sophiakumar** [GothenburgBitFactory/taskwarrior#2367] opened 2020-12-09 08:43 UTC
#### To report a bug...

* output of the ```task diag``` command.
/home/keith/builds/mingw/gcc-9.2.0-mingw32-cross-native/mingw32/libstdc++-v3/include/bits/basic_string.h:1067: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = unsigned int]: Assertion '__pos <= size()' failed.

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by tbabej** [comment] 2020-12-10 04:20
Thank you for letting us know! I assume you are refering to #2024 - which seems to be fixed in 2.5.2. Can you try upgrading to our newest release and see if you can still reproduce the error?

**Comment by tbabej** [comment] 2020-12-29 23:22
As this is likely fixed in the current release, closing for now. Please let us know / reopen if the issue can be reproduced with 2.5.2 or newer release.

**Closed by tbabej** 2020-12-29 23:22 UTC
Labels: awaiting response, bug, cannot reproduce
