### ISSUE TITLE
[TW-1913] Don't store state information in rc file

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1926] opened 2018-02-14 21:29 UTC
_Matthias Beyer on 2017-05-19T11:11:53Z says:_ 

 When setting the context via `task context somecontext`, the current context name gets written to the `taskrc` file.

Because I keep my dotfiles in a git repository, this gets committed some time or my repo is dirty while it actually is not.

The state information for this should not be stored in the rc file, but in some other dotfile which I can put into my `gitignore`.

**Comment by taskwarrior** [comment] 2018-02-14 21:29
Migrated metadata:
```
Created: 2017-05-19T11:11:53Z
Modified: 2017-05-19T20:10:05Z
```

**Comment by jcrben** [comment] 2018-06-16 20:11
This is a duplicate of https://github.com/GothenburgBitFactory/taskwarrior/issues/1990 😄 

You can see a workaround there - my taskrc looks like this:
`include ~/dotfiles/config/task/task.versioned`

**Closed by jcrben** 2018-06-16 20:11 UTC
Labels: enhancement
