### ISSUE TITLE
Tasks spontaneously duplicate themselves

### ISSUE THREAD

**Issue by ulope** [GothenburgBitFactory/taskwarrior#2056] opened 2018-08-21 11:43 UTC
* What command(s) did you run?

Unknown, possibly related to syncing with inthe.am

* What did you expect to happen?

Tasks not to be duplicated

* What actually happened?

*All* not done tasks are duplicated. This is the second time this happened since I started using taskwarrior in May.

* Paste the output of the ```task diag``` command.
```
± task diag
TASKRC override: /Users/ulo/.config/task/taskrc

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Sep 28 2016 03:52:17
      CMake: 3.6.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.15
 Build type: Release

Configuration
       File: /Users/ulo/.config/task/taskrc (found), 2253 bytes, mode 100644
       Data: /Users/ulo/.task (found), dir, mode 40755
     TASKRC: /Users/ulo/.config/task/taskrc
    Locking: Enabled
         GC: Enabled
    $EDITOR: subl -nw
     Server: taskwarrior.inthe.am:53589
         CA: /Users/ulo/.config/task/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: /Users/ulo/.config/task/private.certificate.pem, readable, 2462 bytes
        Key: /Users/ulo/.config/task/private.key.pem, readable, 3660 bytes
    Ciphers: NORMAL
      Creds: inthe_am/ulo/************************************

Hooks
     System: Enabled
   Location: /Users/ulo/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (265x35)
       Dups: Scanned 115 tasks for duplicate UUIDs:
             Found duplicate 7ec3dbfd-1475-47ba-ae63-bc2e519c0970
             Found duplicate 320ce05c-3c98-4633-a17f-e43a77e6c2c4
             Found duplicate 507e2f17-c350-4db9-801e-413438210644
             Found duplicate 05aa2d25-500e-4236-8fd8-a8fd9748c916
             Found duplicate 86c69a9b-26e4-4fe7-8d57-6460e7527006
             Found duplicate e9413f5c-2e64-4e8a-a338-58af9e7a607e
             Found duplicate dfedc009-cb69-445c-a771-2c8b4f849057
             Found duplicate e3bb26b2-e8f3-4156-8f45-ada3466827d4
             Found duplicate 842bd0b3-6bcc-4535-a33e-afe28a470422
             Found duplicate 78f5e3d7-22c9-4ff2-8ef6-31ed09fafab5
             Found duplicate fc6cecd8-afbf-4d36-9cfb-7fe2ad1841f0
             Found duplicate 53ac7536-b504-4d2b-b7a5-418d061dbb9f
             Found duplicate 98293414-1708-40a4-930d-5cb8dafb85ad
             Found duplicate 8bada5da-47bd-4e07-93f9-7feed85cb382
             Found duplicate 510da34e-c4fc-419f-a3d8-6d1356822416
             Found duplicate a83d285d-dcb0-49f9-9c38-1e5daf055d1f
             Found duplicate 8ea314f9-1ef5-4cd1-94ca-78c6c4c1ece8
             Found duplicate fdcdaa2f-9b9d-40f0-9d36-96a6e9dfd7e7
             Found duplicate 3a2b7ed3-b6dd-4ab5-a167-76893cd15682
             Found duplicate 4a550f53-9d01-4ef9-93e8-62e04b29fbf7
             Found duplicate 6308a892-f56d-4d15-95e9-bb2d1b090699
             Found duplicate 46fbdf7a-ecf5-47ca-a7d4-f821b6efcebb
             Found duplicate 6482a025-196f-4c71-9bc4-8c0a72993a57
             Found duplicate e767ed16-640f-4de4-ac86-b0396f3fd6a0
             Found duplicate b61f5fad-5075-4e4c-b03a-acbba519e86f
             Found duplicate 6562c513-525a-4508-a995-0e4251892147
             Found duplicate 9a39e1c5-3cd6-4714-8c04-783486a6e453
             Found duplicate 7a5ba325-6c3f-4e3a-8f44-6df1d2d5ae65
 Broken ref: Scanned 115 tasks for broken references:
             No broken references found
```

**Comment by ulope** [comment] 2018-10-01 12:03
It has happened again. I start to suspect that repeating tasks are somehow involved. I purposefully haven't synced for the last 5 days or so. 

Yesterday (the 30th) everything was fine, today (the 1st) I again am seeing 19 dupes.

**Comment by ddeimeke** [comment] 2018-10-01 13:49
Did you set `recurrence=0` on all but one Taskwarrior clients?

From the manpage:

```
       recurrence=1
              Controls  whether recurrence is enabled, and whether recurring tasks con‐
              tinue to generate new task instances. Defaults to "1".

              If you are syncing multiple clients, then it  is  advised  that  you  set
              'recurrence=1'  on  your  primary client, and 'recurrence=0' on ALL other
              clients. This is a workaround for a duplication bug.
```

**Comment by JonasDralle** [comment] 2018-10-30 13:30
Shouldn't this logic be server-side?

**Comment by arooni** [comment] 2018-11-07 00:20
also affected on mac:

```
[I]  ~  task diag

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Sep 28 2016 03:52:17
      CMake: 3.6.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.15
 Build type: Release

Configuration
       File: /Users/david/.taskrc (found), 15953 bytes, mode 100644
       Data: /Users/david/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: taskwarrior.inthe.am:53589
         CA: ~/.task/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: ~/.task/private.certificate.pem, readable, 2462 bytes
        Key: ~/.task/private.key.pem, readable, 3660 bytes
    Ciphers: NORMAL
      Creds: inthe_am/daveparkinson/************************************

Hooks
     System: Enabled
   Location: /Users/david/.task/hooks
     Active: on-modify.timetracking (executable) (symlink)
             on-modify.timewarrior  (executable)
   Inactive:

Tests
      $TERM: screen-256color (321x61)
       Dups: Scanned 5485 tasks for duplicate UUIDs:
             Found duplicate 8778116c-e504-4066-a219-eca53b6fb6ed
             Found duplicate 8e8d546e-e012-4f7b-a259-018add3588d3
             Found duplicate 7c84d2b3-d807-4cfa-ab47-2898fc8ce7ab
             Found duplicate 1c4ab02b-1b3e-48b9-a564-245ca8a1ba5b
             Found duplicate 4df0a896-b444-4376-8d94-41ff8cabed45
             Found duplicate 32fb2d0f-52a9-443b-91cc-388b69be912b
             Found duplicate d4ccf110-ed7e-4ef4-8d9f-d4fdd3d7d158
             Found duplicate 056945c4-e38e-4979-bc99-6d1fe4c92142
             Found duplicate 2762bc73-698f-47c7-b5de-4214a4b5f21f
             Found duplicate fd059735-6d78-4cef-908a-f917925d32ce
             Found duplicate d576a88a-5ba7-4d7a-b82f-d2877b7be0d9
```

**Comment by meonkeys** [comment] 2019-04-13 18:59
Here's the duplication bug mentioned in the manpage: https://github.com/GothenburgBitFactory/taskserver/issues/46

**Comment by devurandom** [comment] 2019-05-02 10:38
Is this a duplicate of #1649 (which potentially has duplicates in #1962, #1963)?

**Comment by pbeckingham** [comment] 2019-08-12 00:19
Closing as a duplicate.

**Closed by pbeckingham** 2019-08-12 00:19 UTC
Labels: duplicate
