### ISSUE TITLE
cxxbridge related build errors when building offline (Nix)

### ISSUE THREAD

**Issue by doronbehar** [GothenburgBitFactory/taskwarrior#3705] opened 2024-11-27 21:35 UTC
Hello,

On NixOS, when we build packages, we disallow the usage of the internet. Since dependencies of Rust packages such as this and of course the source code itself of packages must be fetched from the internet, we have a mechanism to download in advance all sources required, and use a hash computed from the contents of the fetched sources, to verify these don't change.

So for example the rust dependencies of this package, are all downloaded to a cargo cache, and get a hash. Then this cache is used when we build Taskwarrior (offline, just like any other package).

Weirdly, we get this issue when using the above mechanism (which works well for an uncountable number of packages):

```
error: download of config.json failed
Caused by:
  failed to download from `https://index.crates.io/config.json`
Caused by:
  [6] Could not resolve hostname (Could not resolve host: index.crates.io)
make[2]: *** [src/taskchampion-cpp/CMakeFiles/cxxbridge_v1.0.128.dir/build.make:74: corrosion/cxxbridge_v1.0.128/bin/cxxbridge] Error 101
make[1]: *** [CMakeFiles/Makefile2:617: src/taskchampion-cpp/CMakeFiles/cxxbridge_v1.0.128.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Do you have an idea what exactly that CMake file is trying to download? We should be able to fix our build if CMake will be able to detect that nothing should be downloaded, as the files are already there - because we'll put them there ourselves.

**Comment by djmitche** [comment] 2024-11-27 22:56
`index.crates.io` is where the index to crates is stored. The corrosion extension we use is basically calling `cargo build` with some arguments, I think the `--offline` option skips this check. [Corrosion makes `FROZEN` available](https://corrosion-rs.github.io/corrosion/usage.html), which should help in this case - it is equivalent to `--locked --offline`.

It is probably easy to just patch that option into `src/taskchampion-cpp/CMakeLists.txt` but I'd be happy to merge a PR to add a CMake OPTION to do the same, if you'd refer.

**Comment by doronbehar** [comment] 2024-11-28 07:04
I tried the following:

```diff
diff --git i/src/taskchampion-cpp/CMakeLists.txt w/src/taskchampion-cpp/CMakeLists.txt
index a0d4a42ab..709b1dc3d 100644
--- i/src/taskchampion-cpp/CMakeLists.txt
+++ w/src/taskchampion-cpp/CMakeLists.txt
@@ -19,6 +19,7 @@ endif (ENABLE_TLS_NATIVE_ROOTS)
 corrosion_import_crate(
   MANIFEST_PATH "${CMAKE_SOURCE_DIR}/Cargo.toml"
   LOCKED
+  FROZEN
   CRATES "taskchampion-lib"
   FEATURES "${TASKCHAMPION_FEATURES}")
 
```

And it didn't help - same error.

**Comment by djmitche** [comment] 2024-11-28 13:59
Well, that is disappointing! Can you tell what `cargo` commands it's running? For me (with whitespace added):
```
Run Build Command(s): /usr/bin/ninja -v taskchampion-cpp                                                                                                                                                                                                                                                                       [0/7] cd /home/dustin/p/taskwarrior/src/taskchampion-cpp &&
/usr/bin/cmake -E env
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/cc
  CC_x86_64_unknown_linux_gnu=/usr/bin/cc
  CXX_x86_64_unknown_linux_gnu=/usr/bin/c++
  AR_x86_64_unknown_linux_gnu=/usr/bin/ar
  CORROSION_BUILD_DIR=/home/dustin/p/taskwarrior/build/src/taskchampion-cpp
  CARGO_BUILD_RUSTC=/home/dustin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc
  /home/dustin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo rustc
    --lib
    --target=x86_64-unknown-linux-gnu
    --package taskchampion-lib
    --manifest-path /home/dustin/p/taskwarrior/src/taskchampion-cpp/Cargo.toml
    --target-dir /home/dustin/p/taskwarrior/build/./cargo/build
    --locked
    --
    -Cdefault-linker-libraries=yes
```
perhaps that is interacting poorly with the pre-generated cache?

**Comment by djmitche** [comment] 2024-11-28 14:00
Do either of https://github.com/corrosion-rs/corrosion/issues?q=is%3Aissue+Nix help?

**Comment by doronbehar** [comment] 2024-11-28 14:44
I managed to find out the failing command by printing `build.make` after the `cmake` configure phase was finished, and match that with line `74` from the original failure. This is the command that fails:

```
	cd /build/source/build/src/taskchampion-cpp && /nix/store/4kb60dy0dg80ww8gh2av4by4vwn8l48k-cmake-3.30.5/bin/cmake -E env CARGO_BUILD_RUSTC=/nix/store/xjndavbjpgzkabvnrl8xl6h51pksymfy-rustc-wrapper-1.82.0/bin/rustc /nix/store/6sn3alxhxzwz4q3bbmkh5ywgjj0g8m2a-cargo-1.82.0/bin/cargo install cxxbridge-cmd --version 1.0.128 --root /build/source/build/corrosion/cxxbridge_v1.0.128 --quiet
```

Could it be that adding `cxxbridge-cmd` to the main `Cargo.toml` would help? If you could give me a patch to test that will include the update to the `Cargo.lock` file, it'd be great. I want to know what do you think before I try to do it myself first.

**Comment by djmitche** [comment] 2024-11-28 14:51
Ah, that makes sense -- [it's trying to build the `cxxbridge-cmd` crate](https://github.com/corrosion-rs/corrosion/blob/b816285a706acbf3efa8a946f834ca32e093ff41/cmake/Corrosion.cmake#L1548). I suspect that if you ensure the correct version of cxxbridge is already installed and in PATH, everything will just work. I don't think adding it to Cargo.toml will help.

**Comment by djmitche** [comment] 2024-11-28 14:53
Correction: in $PATH isn't enough - it's looking for that executable in the cargo bin directory
```
    # First check if a suitable version of cxxbridge is installed
    find_program(INSTALLED_CXXBRIDGE cxxbridge PATHS "$ENV{HOME}/.cargo/bin/")
```

**Comment by doronbehar** [comment] 2024-11-28 16:36
OK I managed to fix it, but it was much more hacky then putting a file in a `~/.cargo/bin/`:

```nix
  postConfigure = ''
    _possible_version_cargo_lock_line="$(grep -A1 'name = "cxx"' ${finalAttrs.src}/Cargo.lock | tail -1)"
    if echo "$_possible_version_cargo_lock_line" | grep -q '^version = "'; then
      _cxxbridge_version="$(echo "$_possible_version_cargo_lock_line" | cut -d'"' -f2)"
    else
      echo "cxxbridge hack fatal error: could not find version string" >&2
      exit 1
    fi
    mkdir -p corrosion/cxxbridge_v"$_cxxbridge_version"/bin
    cp ${lib.getBin buildPackages.cxx-rs}/bin/cxxbridge corrosion/cxxbridge_v"$_cxxbridge_version"/bin
  '';
```

From some reason it wouldn't detect the `cxxbridge` executable in `~/.cargo/bin`. I'm pretty sure because our Rust / Cargo related build system hooks use a directory different from `~/.cargo` to hold pre-fetched Cargo dependencies, and `$HOME` is not a real directory in our build system (at least by default).

Anyway, it would be nice to ask one of the players playing here for a favor. Is it `cxxbridge` that I should ask for modifying a bit their cmake macros etc so that the executable `cxxbridge` will be searched from `$PATH` as well? Or does this happen somewhere in Taskwarrior's `CMakeLists.txt`?

**Comment by djmitche** [comment] 2024-11-28 17:17
That seems a reasonable hack :/

I think the fix would be in https://github.com/corrosion-rs/corrosion/blob/master/cmake/Corrosion.cmake#L1548. Note that corrosion considers the cxx support [experimental](https://corrosion-rs.github.io/corrosion/ffi_bindings.html?highlight=cxxbridge#cxx-integration). But maybe they would accept a patch to add a CXXBRIDGE arg to that function which overrides the auto-detection? My CMake skills are minimal, so I don't think I'd be a good person to try that.

**Comment by doronbehar** [comment] 2024-11-28 17:18
OK thanks for the links anyway, I'll see if I'll find time to work on this...

**Comment by djmitche** [comment] 2024-11-28 17:27
It's worth filing a bug for even if you can't work on it!

**Comment by doronbehar** [comment] 2024-11-29 10:11
HMM You know I think I might be able even without corrosion fixing their `$PATH` search to be able to use our corrosion, by using the cmake variable `INSTALLED_CXXBRIDGE`. However, that would not work, as corrosion is making a strict version check for the cxxbridge installed / available. Our current `cxx-rs` package that provides the `cxxbridge` command is pretty old (`1.0.92`), and updating it to the latest version (`1.0.131`) also will not work because it will be checked against `1.0.128` which is the version currently used here...

I just checked, and simply putting `cxxbridge` of version `1.0.128` in `$PATH` while building `taskwarrior` makes it work! The only challenge left for me as a distributor is to make sure that your requested `cxx` version from the `Cargo.lock` file is the same as the one we build and distribute by ourselves. This is especially challenging as `cxx` as they don't even Git track their `Cargo.lock` file (which we must vendor due to our offline build limitations), and the fact that `cxx` release are pretty frequent...

**Comment by doronbehar** [comment] 2024-11-29 10:13
I think we can close this, as there is nothing for you to do here, except perhaps I can ping you here to update the corrosion dependency if they'll agree to modify that strict version check...

**Comment by jschwe** [comment] 2024-11-29 10:58
@doronbehar I just quickly skimmed this thread, but you can use `cargo metadata` or `cargo tree -i cxx --depth=0` to get the version of `cxx` that taskwarrior depends on, and install that version in your configure stage (that still has internet access as i understand). e.g. `cargo install cxxbridge-cmd --version ${parsed_version}`.
(The lockfile from taskwarrior is the important one, it doesn't matter that `cxx` doesn't have a lockfile)

**Comment by djmitche** [comment] 2024-11-29 14:29
FWIW, the strict version requirement is correct -- `cxxbridge-cmd` is building C++ code to interface with the `cxx` library code, and the two must be co-versioned. Generating output with 1.0.128 and compiling that against a 1.0.129 library would lead to bugs!

I'll close this as suggested but if discussion continues we can re-open.

**Comment by djmitche** [comment] 2024-12-08 21:47
Per [this comment](https://github.com/GothenburgBitFactory/taskwarrior/pull/3716#issuecomment-2525595415) the work in this issue is done. There's still #3707, and maybe more work required to get all of this done, but we can open new issues for that.

**Comment by doronbehar** [comment] 2024-12-17 14:11
Glad to report that after investigation the `cxxbridge-cmd` issue was easily fixed via simply setting `CARGO_HOME` to a correct value. Now continue to debug #3707 .

**Comment by jrmarino** [comment] 2024-12-28 23:53
I started the topic on corrosion.  I haven't been able to build with offline sources even with the suggested hacks.

I built cxxbridge separately (which was not easy) and set INSTALLED_CXXBRIDGE in cmake, but now taskwarrior is complaining about cxx being missing. Now I'm not sure if cxxbridge + cxx versions have to be exactly what's bundled with taskwarrior releases.

I've literally spent hours and hours on this - If taskwarrior can't be easily maintained with offline sources, it might be time to just drop it. It looks like the issue is considered solved so there's no relief at Ravenports.

sorry. the maintenance on this for source-building repos is so heavy starting with version 3.2.0.

**Comment by djmitche** [comment] 2024-12-30 03:01
This sounds frustrating!

I do think the cxxbridge and cxx versions must match exactly, and must match what is specified in the Taskwarrior Config.toml. I don't think Taskwarrior is _particularly_ sensitive to which version that is, so if you wanted to patch Cargo.toml to match the version available in the distro, that would probably be OK as long as that version is "similar".

I'm not sure what Ravenports is, or what issue is considered solved?

How can I help? My understanding of CMake and its config files is limited at best, so I don't know if I can make a fix -- but I'm happy to advocate with various maintainers (corrosion, cxx, etc.) to adopt patches, if that helps.

**Comment by ryneeverett** [comment] 2024-12-30 03:45
> If taskwarrior can't be easily maintained with offline sources, it might be time to just drop it. It looks like the issue is considered solved so there's no relief at Ravenports.

I believe this is a misunderstanding because it appears that Nix *is* successfully building taskwarrior 3.2 offline: https://github.com/NixOS/nixpkgs/pull/359893.

**Comment by jrmarino** [comment] 2024-12-30 04:55
The Nix maintainer also spent hours on this and somehow hacked it in the end.  It appeared that they built a version of cxxbridge separately and used that.  I tried that, and then got hit with a missing "cxx" error.   At this point, I gave up because taskwarrior clearly can't be easily built with pre-fetched sources and I was not sure that my version of cxxbridge (1.0.36) could be used since taskwarrior was bundled with 1.0.33.

There is no misunderstanding @ryneeverett - I know NixOS figured it out, but it's not officially documented so I can't follow exactly what he did and frankly, should I have to?

**Comment by jrmarino** [comment] 2024-12-30 05:02
> This sounds frustrating!
> 
> I do think the cxxbridge and cxx versions must match exactly, and must match what is specified in the Taskwarrior Config.toml. I don't think Taskwarrior is _particularly_ sensitive to which version that is, so if you wanted to patch Cargo.toml to match the version available in the distro, that would probably be OK as long as that version is "similar".
> 
> I'm not sure what Ravenports is, or what issue is considered solved?
> 
> How can I help? My understanding of CMake and its config files is limited at best, so I don't know if I can make a fix -- but I'm happy to advocate with various maintainers (corrosion, cxx, etc.) to adopt patches, if that helps.

so for all our rust-based ports a script figures out which crates to download from Cargo.lock, puts them in a location known to cargo so cargo can build from the Cargo.toml file.  This worked fine with Taskwarrior 3.1.0, but starting with 3.2.0 we got the same error on the top post of this issue.

I don't know exactly what corrosion does, but it would be nice if upstream could pre-generate what it needs and provide it in a release distribution file so Cargo can build it without having to worry about corrosion.  I'm not sure if that's possible but I am sure more package repositories in addition to [Ravenports](http://www.ravenports.com) would benefit from that.

or at the very very least the project should document in a readme file on how to properly build taskwarrior from source with prepositioned crates (due to intentionally blocked internet connection).

**Comment by doronbehar** [comment] 2024-12-30 09:55
> The Nix maintainer also spent hours on this and somehow hacked it in the end.

It wasn't such a sophisticated hack in the end. I simply had to find the directory that our ecosystem uses as the place where all the Cargo dependencies where downloaded, and point `CARGO_HOME` to it.

Because most of the work was to reverse engineer our ecosystem's offline rust builds mechanisms, it didn't feel like taskwarrior could have helped a lot. I agree though, that it is not trivial to find build instructions in general (I didn't find easily), and not to mention this pretty important detail.

**Comment by djmitche** [comment] 2024-12-30 13:59
I don't think Taskwarrior does anything all that unusual -- it's a pretty straightforward application of cxx. Perhaps other ports of applications that use cxx have similar solutions, or documentation?

I'm happy to add documentation, but I don't think I understand the problem well enough to write those docs :)

**Comment by jrmarino** [comment] 2024-12-30 15:18
I guess my first question is why is cxx/cxxbridge bundled?
The "problem" is the root cargo.toml alone will not build taskwarrior.  It's missing the dependencies needed to build cxxbridge (and apparently cxx).

so taskwarrior is doing something very unusual.  Every other rust-based port we have only needs the root cargo.lock and cargo.toml files.

So the second observation is - if taskwarrior has a more complex build process (in this case building building cxxbridge and cxx) then maybe it should be using a makefile to chain these steps together - at least for the case where files have to be prefetched which is a requirement for NixOS, Ravenports, FreeBSD Ports, and probably many others.

**Comment by doronbehar** [comment] 2024-12-30 15:21
> I guess my first question is why is cxx/cxxbridge bundled?
> The "problem" is the root cargo.toml alone will not build taskwarrior. It's missing the dependencies needed to build cxxbridge (and apparently cxx).

That's not my observation. In Nix, after downloading all dependencies specified in `Cargo.lock`, they included `cxxbridge`.

**Comment by jrmarino** [comment] 2024-12-30 15:28
That's not true.  the root Cargo.lock does not contain dependencies for the corrosion component, so at the very least the 2 sets of dependencies have to be combined.

Moreover, to get it to build in the environment, the builder needs a custom path/.cargo/config  to define the "source.crates-io" and directory where these crates are located, but when corrosion tries to build, it doesn't use this configuration - so maybe a second config is needed.

In any case -- if NixOS solved this, just document step for step what's needed and then maybe others can follow suit.

**Comment by doronbehar** [comment] 2024-12-30 15:52
> That's not true. the root Cargo.lock does not contain dependencies for the corrosion component, so at the very least the 2 sets of dependencies have to be combined.

What dependencies do you see here missing?

```
$ git grep 'name = "cxx' Cargo.lock
Cargo.lock:name = "cxx"
Cargo.lock:name = "cxx-build"
Cargo.lock:name = "cxxbridge-flags"
Cargo.lock:name = "cxxbridge-macro"
```

> Moreover, to get it to build in the environment, the builder needs a custom path/.cargo/config to define the "source.crates-io"

That's true, and Nixpkgs does it for every Rust based package, Taskwarrior is not special in that aspect.

**Comment by jrmarino** [comment] 2024-12-30 15:58
we are going around in circles.
I said that for every other rust-based port, we only need to preposition crates for ones listed in the Cargo.lock file (usually there's only one).  That doesn't work here.  we get the error you showed on the first post.  
So what's the fix?

**Comment by djmitche** [comment] 2024-12-30 17:34
To clarify, cxx is a bridge from Rust to C++, so this would probably not occur in every rust-based port, but only those which use cxx to mix C++ and Rust. Before 3.2.0, Taskwarrior used a hand-rolled (and buggy) interface between Rust and C++, but began using cxx in 3.2.0.

There were a few fixes in 3.3.0 to make this easier: dfc36aefcfc5896bc67d309d1289265eee992303 and c2cb7f36a710913787e5b5e9b26e6846ed89e30b. The first, in particular, uses an updated version of the cxx-build dependency which includes transitive dependencies on the same version of cxxbridge-cmd.

AIUI there are two parts here:
 - make sure the right version of the source of the crate cxxbridge-cmd is available 
 - make sure that crate is built and the executable is in a place where the build process will find it

I believe dfc36aefcfc5896bc67d309d1289265eee992303 handles the first, I believe @doronbehar accomplished the second with the fix mentioned [a few hours ago](https://github.com/GothenburgBitFactory/taskwarrior/issues/3705#issuecomment-2565260321). And as mentioned, that's mostly because the ecosystem's offline rust build system sets an unusual CARGO_HOME, rather than anything particularly unusual Taskwarrior is doing. Maybe a link to that fix can help @jrmarino make progress?

Some things that might help outside of the ecosystem:
 - Update corrosion to support some kind of CXXBRIDGE_CMD_BIN env variable that can just point to the binary, avoiding all of the search and any issues about CARGO_HOME
 - Update Taskwarrior build docs to point to the corrosion docs
 - Update Corrosion docs to be more clear about the requirements and how this search works

What do you think?

**Comment by jschwe** [comment] 2024-12-30 18:40
> make sure that crate is built and the executable is in a place where the build process will find it

To clarify: the `cxxbridge` executable must be **exactly** the same version as specified in the lockfile. 

One difference here is that corrosion / taskwarrior uses a `cxxbridge` **commandline tool**, which needs to be either installed beforehand or built from source during the build. In the broader ecosystem that does not use CMake, cxxbridge is often used as a library from build scripts. This is mainly necessary, since corrosion / CMake wants to know which (header) files get generated, which would be difficult if they are just byproducts from an opaque build script. 

> Update corrosion to support some kind of CXXBRIDGE_CMD_BIN env variable that can just point to the binary, avoiding all of the search and any issues about CARGO_HOME

Corrosion searches for `cxxbridge` in `PATH`, so I don't think such an environment variable would help much. I think the `CARGO_HOME` thing is about when `cxxbridge` is not installed OR the version does not match the required version. In this case the `cxxbridge-cmd` binary needs to be built from source first.
As I understand based on the previous discussion (I have not tested this myself) setting `CARGO_HOME` (or alternatively probably also an override for the crates.io registry) allows `cargo install cxxbridge-cmd` to use the local vendored sources for an offline build instead of fetching from crates.io.

> Update Corrosion docs to be more clear about the requirements and how this search works

Improvements to the corrosion documentation regarding offline builds would definitely be useful.

**Comment by jrmarino** [comment] 2024-12-30 18:51
would a 2-stage build work?
Meaning stage 1 would build and install cxxbridge-cmd (and cxx??) from the bundled sources and then a standard build would work because these tools are in the path?

I actually built v1.0.36 of cxxbridge and had it available to taskwarrior which seemed happier, but I got a new error of a missing "cxx" at which point I threw my hands up in frustration after several hours of this.

I'm loathe to split taskwarrior into multiple packages with a common distfile (e.g. cxx/cxxbridge as a dependency package to taskwarrior itself) but I've done it before.

Apparently none of the other rust-based ports incorporate c++ in this way or use corrosion because I definitely have not hit this problem before and this is a magnitude more work to maintain.  There's nothing normal about it (in my experience).

**Comment by djmitche** [comment] 2024-12-30 21:19
Thanks for the updates @jschwe, and apologies for my confusion about CARGO_HOME (based on [my comment earlier in this issue](https://github.com/GothenburgBitFactory/taskwarrior/issues/3705#issuecomment-2506301029)).

> In the broader ecosystem that does not use CMake, cxxbridge is often used as a library from build scripts. This is mainly necessary, since corrosion / CMake wants to know which (header) files get generated, which would be difficult if they are just byproducts from an opaque build script.

Looking at `Corrosion.cmake` and unpacking this for my understanding: CMake needs to know how to create `"${header_placement_dir}/${cxx_header}` and `"${header_placement_dir}/${cxx_source}`, since other C++ code will depend on those. Usage as a library would be from taskchampion-lib's `build.rs`, which would mean that these files appear when that `build.rs` is run by `cargo build`, and it's difficult to indicate that to CMake. Do I have that about right?

If we think of `cxxbridge-cmd` as a build requirement, it is an unusual one in that the _precise_ version must be supplied. Other build-time requirements like `yacc` or Clang allow version ranges, and are typically supplied by other distro packages in a distro's build process.

So, there are a few options, and I'm not sure which would be preferred by no-internet build systems:
 - Package `cxxbridge` separately and require the exact version as a build dependency. AIUI, I think this is similar to the "split taskwarrior into multiple packages with a common distfile" solution, above, except that solution would package `cxxbridge` a a taskwarrior-related package.
 - Build the correct version of the `cxxbridge` binary as part of the Taskwarrior build process, position it somewhere accessible, and make sure the Taskwarrior cmake invocation finds it. Is this is the "2-stage build" idea? I guess it would mean that during the configure stage (with internet access), all of the necessary crates for both Taskwarrior and the `cxxbridge` binary would be pre-positioned. I think dfc36aefcfc5896bc67d309d1289265eee992303 accomplishes this for the most part, assuming the pre-positioning process includes `build-dependencies`. Then during the build stage, run `cargo install --offline cxxbridge-cmd` followed by `cmake --build build`.
 - Let corrosion run `cargo install cxxbridge-cmd` as part of the `cmake --build build` invocation.

The last option is the "well-lit path" for normal internet-accessible builds of Taskwarrior, with Corrosion taking pains to make it work regardless of what it finds. But it causes problems for no-internet builds. Critically, it's not running `cargo install --offline cxxbridge-cmd` (missing the critical `--offline`).

I suspect that just-make-it-work behavior is at cross-purposes with the high degree of control desired in no-internet build situations. So maybe one of the first two options is a better choice: supply the needed binary precisely, and disable Corrosion's just-make-it-work behavior.

But my comments are at a very "how should this work" level. But I sense some frustration, @jrmarino, so if you'd like to instead focus on the shortest path to getting this built, we can do that too - probably starting with what got you the 'new error of a missing "cxx"'. For this path, let's open a new issue with that error and enough background for someone who's never heard of Ravenports to figure out what is going on.

**Comment by jrmarino** [comment] 2024-12-30 22:15
Well, knowledge of Ravenports isn't necessary.  The important thing to know is that the build environment is reproducible and all dependencies are pre-installed, and all necessary distribution files are pre-fetched into known positions.  This is a common scenario.  I have no NixOS experience, but it sounds like it is similar - just as building on poudriere on a FreeBSD system would be similar.

I (and any maintainer on any of these package repos) are pretty flexible and we normally can conform to the build requirements of a package.  The issue here is the build process for offline builds hasn't been tested, defined, or documented.  Once a procedure is defined, I can figure out how to accomplish it.

I suspect everyone here is more knowledgeable about building rust projects than I am, so a lot of the frustration you hear is due to this problem exceeding my basic cargo knowledge and the fact I know nothing about corrosion / cxx / cxxbridge / etc.   I'm just trying to get taskwarrior building again.

so if someone comes up with the build procedure for this scenario (and hopefully documents it) that would probably be enough for me and others like me.

**Comment by doronbehar** [comment] 2024-12-30 22:37
@jrmarino I feel your frustration, and the truth is that the experience for me with NixOS wasn't pleasant as well. Perhaps I'd be able to help you if you'd describe to us how does your build scripts deal with the most typical Rust projects (e.g [`mdzk`](https://github.com/mdzk-rs/mdzk)). How does your ecosystem prefetches the Cargo dependencies? How does it read the `Cargo.lock` file in order to do that? In what format does it save the prefetched Cargo dependencies? (A tarball? Or a directory? Or perhaps a tarball that is then extracted?) These are the kind of questions I asked while investigating the issue with Nixpkgs' build scripts etc. If you'd describe for us how does your ecosystem does that for a pretty simple package such as [`mdzk`](https://github.com/mdzk-rs/mdzk) I might be able to help

**Comment by jrmarino** [comment] 2024-12-30 22:54
alright, I'll illustrate with b3sum.  Here's a compiled specification sheet:
https://raw.githubusercontent.com/Ravenports/Ravenports/master/bucket_03/b3sum

During the fetch phase, the 57 distribution files are downloaded to a local directory (assuming they weren't previously downloaded).

During the extraction phase, each crate is extracted and then moved to the $CARGO_VENDOR_DIR which is defined as the "cargo-crates" subdirectory of the b3sum distribution (e.g. /construction/b3sum/b3sum-1.5.5/cargo-crates)

For each crate, a dummy .cargo-checksum.json file is created, for example
```
@${MV} ${WRKDIR}/rayon-core-1.12.1 ${CARGO_VENDOR_DIR}/rayon-core-1.12.1
@${PRINTF} '{"package":"%s","files":{}}' $$(${SHA256} -q ${DISTDIR}/${DIST_SUBDIR}/rayon-core-1.12.1.tar.gz) > ${CARGO_VENDOR_DIR}/rayon-core-1.12.1/.cargo-checksum.json
```

The default configure target is this:
```
do-configure:
        @${ECHO_MSG} "===>   Cargo config:"
        @${MKDIR} ${WRKDIR}/.cargo
        @: > ${WRKDIR}/.cargo/config.toml
        @${ECHO_CMD} "[source.cargo]" >> ${WRKDIR}/.cargo/config.toml
        @${ECHO_CMD} "directory = '${CARGO_VENDOR_DIR}'" >> ${WRKDIR}/.cargo/config.toml
        @${ECHO_CMD} "[source.crates-io]" >> ${WRKDIR}/.cargo/config.toml
        @${ECHO_CMD} "replace-with = 'cargo'" >> ${WRKDIR}/.cargo/config.toml
        @${CAT} ${WRKDIR}/.cargo/config.toml

        @if ! ${GREP} -qF '[profile.release]' ${CARGO_CARGOTOML}; then \
                ${ECHO_CMD} "" >> ${CARGO_CARGOTOML}; \
                ${ECHO_CMD} "[profile.release]" >> ${CARGO_CARGOTOML}; \
                ${ECHO_CMD} "opt-level = 2" >> ${CARGO_CARGOTOML}; \
                ${ECHO_CMD} "debug = false" >> ${CARGO_CARGOTOML}; \
        fi
        @${ECHO_MSG} "===>   Updating Cargo.lock"
        ${CARGO_CARGO_RUN} update \
                --manifest-path ${CARGO_CARGOTOML} \
                --verbose \
                ${CARGO_CONFIG_ARGS}
.endif
```

The standard build target is
```
do-build:
        ${CARGO_CARGO_RUN} build \
                --manifest-path ${CARGO_CARGOTOML} \
                --verbose \
                ${CARGO_BUILD_ARGS}
.endif
```

So that's a typical rust port.  There are some tricky python+rust ports that need some customization, but generally it's a variation of this.


Trying this technique on taskwarrior gets pretty far until I hit the error seen in the first post.

(The distribution file information is derived from Cargo.lock)

I'm guessing NixOS has comparable manipulations ...

**Comment by doronbehar** [comment] 2024-12-30 23:38
OK so yes your technique with the `.cargo/config.toml` looks pretty similar to what we do. I'd suggest to try the following:

- Run the above configure target, and then run the configure target used for standard CMake projects. 
- After both configure targets are finished, try to set `$CARGO_HOME` to `${WRKDIR}/.cargo`.
- Run the build target suitable for standard CMake projects.

**Comment by jrmarino** [comment] 2024-12-31 04:27
good news, that worked.
I enabled the cargo configure target to run after the cmake configure target (cargo target was disabled before)
The $CARGO_HOME definition was critical.  without it, the build failed.

That's all I did - added the cargo configure target and defined CARGO_HOME and then everything built as expected.

**Comment by djmitche** [comment] 2024-12-31 04:36
Awesome! Where could we add a bit of documentation to help the next prepositioned-source distro maintainer figure this out more quickly, without confusing folks who do not have that role? I'd love an answer in the form of a PR :)

**Comment by doronbehar** [comment] 2024-12-31 11:36
> Awesome! Where could we add a bit of documentation to help the next prepositioned-source distro maintainer figure this out more quickly, without confusing folks who do not have that role? I'd love an answer in the form of a PR :)

Glad I could help :) I think it'd be nice first to change a bit the ["developers" documentation](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/README.md) so that it won't invite only code contributors, but also package distributors.

**Comment by jrmarino** [comment] 2024-12-31 15:02
My opinion is adding a new section of the INSTALL file to cover this topic would be sufficient.  Maybe I'll take a crack at it (in the form of a PR) later today.

**Comment by djmitche** [comment] 2024-12-31 20:27
Thanks for this!!

**Closed as completed by djmitche** 2024-12-31 20:27 UTC
Labels: build-system, topic:distros
