### ISSUE TITLE
"`[/usr/bin/task next]` keeps getting inserted to `task` output

### ISSUE THREAD

**Issue by Granitosaurus** [GothenburgBitFactory/taskwarrior#2226] opened 2019-10-27 03:53 UTC
`[/usr/bin/task next]` string keeps getting inserted randomly in stdout when calling `task` command, e.g.:

```
$ task      

ID Age Tag   Description                    Urg 
 1 10d work  ----------------------------  0.85
 2 10d book  ----------------------------  0.85
 3 5d  work  ----------------------------  0.83
 4 5d  work  ----------------------------  0.83
 5 4d  work  ----------------------------  0.82
[/usr/bin/task next]
 6 4d  work  ----------------------------  0.82
 7 4d  work  ----------------------------  0.82
 8 1d  work  ----------------------------  0.81
 9 1d  floss ----------------------------  0.81
10 18h work  ----------------------------   0.8

10 tasks
```

It's really distracting, sometimes it's in the middle of the list, sometimes at the beginning or end.

task diag:
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 8.2.1 20180831
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov  9 2018 23:33:36
      CMake: 3.12.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.19
 Build type: 

Configuration
       File: /home/dex/.taskrc (found), 1380 bytes, mode 100644
       Data: /home/dex/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/dex/.task/hooks
             (-none-)

Tests
      $TERM: xterm-kitty (166x23)
       Dups: Scanned 84 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 84 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment] 2021-04-09 22:26
Hi @Granitosaurus,

this is quite unusual. I would be interested in seeing how to configure environment for this to happen (I can't reproduce myself), however, as a fix for this issue, you might want to disable the `header` verbosity token (see `man taskrc`, the section about `rc.verbose`)

**Closed** 2024-05-27 21:52 UTC
