### ISSUE TITLE
[TW-1941] rc.verbose=uuid only used if first argument on cmdline (2.6.0)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1953] opened 2018-02-14 22:08 UTC
_Paul Fenwick on 2017-12-23T04:28:10Z says:_ 

 Using 2.6.0, specifying `rc.verbose=new-uuid` works as expected when it's the first argument on the cmdline:

{code}
$ task rc.verbose=new-uuid rc.confirmation=no add Test task pls delete
Created task 633bf2c9-e27b-4c8d-8550-4ff7a05b1ea9.
{code}

However when it's not the first, it seems to be ignored:

{code}
$ task rc.confirmation=no rc.verbose=new-uuid add Test task pls delete
Created task 63.
{code}

In both cases running `task ... show verbose` shows that it's been set correctly, so there something very odd going on and I'm yet to figure out why.

Version info:

{code}
$ task _version
2.6.0 (58ec6735)
{code}

Relates to (or at least adjacent to) TW-1938, and fully explains why `taskw.py` was sometimes but not always having problems on task creation.

**Comment by taskwarrior** [comment] 2018-02-14 22:09
Migrated metadata:
```
Created: 2017-12-23T04:28:10Z
Modified: 2018-01-09T14:08:19Z
```

**Comment by taskwarrior** [comment] 2018-02-14 22:09
_Paul Fenwick on 2017-12-23T04:29:28Z says:_ 

 Guess who just wrote their bug report in the first textbox they saw, and now everything is in the environment field?

**Comment by taskwarrior** [comment] 2018-02-14 22:09
_Paul Fenwick on 2017-12-23T05:07:19Z says:_ 

 Update: From some simple printf-debugging it looks like when the bug triggers the `new-uuid` verbosity level gets lost before `CmdAdd::execute()` gets called. I'm not sure where it's getting lost yet.

**Comment by taskwarrior** [comment] 2018-02-14 22:10
_Paul Fenwick on 2017-12-23T05:28:40Z says:_ 

 Aaaaaaand I've found what's going on. It's from a previous patch having unexpected side-effects.

In `CLI2.cpp` we check for an `override` verbosity level (enabled by default), and we don't report cmdline overrides if it's set. This is great for things like using taskwarrior in one's shell prompt, but setting options like `rc.hooks` to be off so it runs after.

However if we check the context for this verbosity token, and our context hasn't built its verbosity tokens yet, then it will initialise them using the defaults. Later, when our `rc.verbose` override arrives, it gets set in config, but the context's verbosity structure does not get rebuilt. Thus everything seems to be fine in `task show`, but actually isn't fine under the hood.

This is a bother, and I guess we should either try to trigger a rebuild of the verbosity structure if we see it getting set, have an environment variable or similar control the suppression of override reporting, or some third option I haven't yet considered.

**Comment by taskwarrior** [comment] 2018-02-14 22:10
_Paul Beckingham on 2018-01-09T14:08:19Z says:_ 

 Still trying to wrap my head around this.

**Comment by pbeckingham** [comment] 2018-02-16 18:53
This is because `uuid` looks like a DOM ref, which are evaluated left-to-right on the CLI.  Yuck.

**Comment by tbabej** [comment] 2021-06-19 11:53
@pjf @vrusinov @EdwardBetts

This is now fixed on 2.6.0:
```
make RELEASE=2.6.0 reproduce
Generating run-reproduce
sha256:018cae971b49823c4ed8a669a3134e9a905098a7adee84b34e28ebe81bc4efe8
[warrior@tw-2.6.0 ~]$ task rc.verbose=new-uuid rc.confirmation=no add Test task pls delete
Created task 9f487469-3620-4757-80a5-a0ef357f967e.
[warrior@tw-2.6.0 ~]$ task rc.confirmation=no rc.verbose=new-uuid add Test task pls delete
Created task 84fb093c-3e1e-4789-b36c-2e208e1faadd
```

**Closed by tbabej** 2021-06-19 11:53 UTC
Labels: enhancement

**Comment by danielkza** [comment] 2021-07-12 13:52
Can we please backport this fix to 2.5.x? As a new user, I found it quite puzzling to try to set up taskwarrior with bugwarrior for the first time, meet this issue, then find the only fix is to revert to a version from 5 years ago, or use an unstable version.

**Comment by tbabej** [comment] 2021-07-12 14:01
@danielkza The 2.6.0 should not be that far our, perhaps couple of months, so I'm not sure if releasing another 2.5.x patch release so close would be worth the overhead. Part of the problem is that it's not clear which commit fixed the issue above - if you could figure that out with `git bisect`, the chances of doing another patch release would increase :slightly_smiling_face:

**Comment by tbabej** [comment] 2021-09-25 21:39
For the record, I suspect this had the same underlying cause as #2247.
