### ISSUE TITLE
I can't build 3.0 on ubuntu (pop_os)

### ISSUE THREAD

**Issue by simonlearnscoding** [GothenburgBitFactory/taskwarrior#3434] opened 2024-05-02 09:54 UTC
I downloaded 3.0 and running cmake . -DCMAKE_BUILD_TYPE=Release I get and 101 error on the call stack  _deps/corrosion-src/cmake/CorrosionGenerator.cmake

**Comment by djmitche** [comment] 2024-05-02 15:47
Could you copy/paste the whole error?

**Comment by felixschurk** [comment] 2024-05-07 21:50
@simonlearnscoding 
You should also opt for an out-of-source build over e.g.
`cmake -S . -B build -DCMAKE_BUILD_TYPE=Release` 

More detail can be seen in [Development.md](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/development.md#basic-building).

**Comment by simonlearnscoding** [comment] 2024-05-08 07:59
hey I just wanted to tell you that I was able to build by pulling and then checking out the stable branch but it seems like the default download link that is provided in the website might not link to stable by default

**Comment by djmitche** [comment] 2024-05-08 11:46
Oh, I bet you downloaded the zip or tar file provided automatically by GitHub? The `task-x y.z.tar.gz` is the only one that works. The others are just the result of `git archive`.

**Comment by felixschurk** [comment] 2024-05-08 11:56
I guess he was refering to the link on the [homepage](https://taskwarrior.org/) for the downloads, there still is the `3.0.0` in `tar.gz` linked as latest stable.
The link leads to https://taskwarrior.org/download/task-3.0.0.tar.gz

**Comment by simonlearnscoding** [comment] 2024-05-08 18:41
Yes exactly that's where I got it from

**Comment by djmitche** [comment] 2024-05-09 01:22
You'll want to install 3.0.2 from https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v3.0.2.

It looks like https://github.com/GothenburgBitFactory/tw.org/pull/800 fixes a bug that was causing taskwarrior.org not to update. And, https://github.com/GothenburgBitFactory/tw.org/pull/801 adds 3.0.2 to the site.

It seems this is a duplicate of #3294. It's helpful when reporting an error to include the entire error, as text. That would have helped us narrow this down sooner!

**Closed as completed by djmitche** 2024-05-09 01:22 UTC
