### ISSUE TITLE
[TW-1907] Can't sync: "The status 'aitin' is not valid."

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1920] opened 2018-02-14 21:18 UTC
_MartyLake on 2017-04-12T12:21:31Z says:_ 

 After trying to use recurrence, I had issues and deleted most of my recurrent issues (if not all). I issued a task sync, tried to modify some files about some parent missing, and blocked everything.

Since then, I deleted my local task data to start again with a clean state, but I've got the following messages:

"11:56 mbp-de-marty ~ > task sync init
Please confirm that you wish to upload all your pending tasks to the Taskserver (yes/no) yes
Warning: You have specified that the 'entry' date is after the 'end' date.
Warning: You have specified that the 'wait' date is after the 'due' date.
The status 'aitin' is not valid.

11:56 mbp-de-marty ~ > task sync     
Warning: You have specified that the 'entry' date is after the 'end' date.
Warning: You have specified that the 'wait' date is after the 'due' date.
The status 'aitin' is not valid."

For now, I can still use the Mirakel android app to deal with my tasks, but it's so slow I would prefer using the CLI task app when I have access to a computer. :(
Best,

**Comment by taskwarrior** [comment] 2018-02-14 21:19
Migrated metadata:
```
Created: 2017-04-12T12:21:31Z
Modified: 2017-04-23T15:26:37Z
```

**Comment by taskwarrior** [comment] 2018-02-14 21:19
_Dirk Deimeke on 2017-04-12T12:32:10Z says:_ 

 In my opinion the status should be "waiting" not "aitin". 

BTW: Mirakel kicked Taskserver support ...

**Comment by taskwarrior** [comment] 2018-02-14 21:19
_Paul Beckingham on 2017-04-12T21:30:54Z says:_ 

 I think Mirakel dropped Taskserver support over a year ago, and stopped fixing various related bugs before that.

**Comment by taskwarrior** [comment] 2018-02-14 21:19
_MartyLake on 2017-04-19T21:51:43Z says:_ 

 I'm using Mirakel 2.8.2, last known android app that works with TW :)

Do you think it may be the source of my problems ? Do you have any recommandations about how to recover and avoid this situation in the future ?

**Comment by taskwarrior** [comment] 2018-02-14 21:20
_Paul Beckingham on 2017-04-20T00:54:56Z says:_ 

 Mirakel was the first android app that works with Taskwarrior, certainly not the last.

Yes, I do think it's the cause of problems, there have been several issues reported by users.  In particular, the title of this issue is something I've heard before from a Mirakel client.  The only suggestion I can make is to restore from backup.  I can't suggest fixes for software I don't know.

**Comment by taskwarrior** [comment] 2018-02-14 21:20
_MartyLake on 2017-04-20T08:47:33Z says:_ 

 I understand that you can't suggest fixes for software you don't know. 

Can you advice me about the «restore from backup» procedure, and how can I use TW on Android ? Do I have to create a new FreeCinc account and start again from here ?

Best,

**Comment by taskwarrior** [comment] 2018-02-14 21:20
_MartyLake on 2017-04-23T15:26:37Z says:_ 

 HeadsUp: managed to install and configure Konstantin's android port. I've created a new FreeCinc account and will move manually all tasks from old broken FreeCinc account to this new one. Also disabled recurrence globally: I will use a different task manager (incidentally called "Tasks") on Android for recurrent tasks.

Thanks for your help !

**Comment by jcrben** [comment] 2018-04-21 21:16
Since this seems like a Mirakel issue, might be worth closing as `not a bug`.

**Comment by pbeckingham** [comment] 2018-05-12 16:53
Thanks @jcrben.

**Closed by pbeckingham** 2018-05-12 16:53 UTC
Labels: not a bug
