### ISSUE TITLE
[TW-1850] Adding a task with \' between \" breaks sync with taskserver

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1865] opened 2018-02-14 19:53 UTC
_Wenceslao Grillo on 2016-09-06T16:27:56Z says:_ 

 I added a task. My desired description was:

Blah blah "quoted text that says Don't"

So I run:

task add "Blah blah \"quoted text that says Don\'t panic and carry a towel\"" +tag1 +tag2

and every sync after that failed with error:
 The Taskserver returned error: 500 Unrecognized taskwarrior file format.

otherwise, taskwarrior seemed to be OK.

STEPS I WENT THROUGH:

This was one of 629 tasks that I added one after the other with a script. I did not check how that "don't" looked like.

I did a:
task export
to save all those new tasks (I didn't need it later), then went into the .taskrc directory and removed all the .data files. Then a sync worked and brought all my tasks from before that crazy script, from taskserver into taskwarrior.

Then I ran the first 50 adds, and a sync (succesful) then 50 more adds and another sync. Until one sync gave the same error.
Deleted the *.data files again. sync to get all the tasks from the server (including the first few batches of 50). And did 10 adds, sync, 10 adds, sync until it crashed again.
Deleted *.data, sync to get everything back except the last batch of 10, and went one by one, until it crashed on the "don't" task.

That time it gave me a different error, but it was too late at night and I didn't save it.

Removing the "\" before the " ' " fixed the problem, and the rest of the adds went OK, and now it's syncing with all and the 629 tasks. 

SUGGESTIONS:
Something is not getting escaped as it should. If that \ wasn't necessary, I should have got it as part of the description (perhaps escaped as \\ in the file...), but the sync shouldn't break.

This way of deleting all the .data files is a bit violent, I lost the undo and perhaps something else (I don't care), but I think it could be refined a bit and made into a standard procedure recommended somewhere in the help as a way of getting over these sync problems that seem to be relatively common... perhaps with an export with some format before... but it solves the problem, and helps isolate the cause.

**Comment by taskwarrior** [comment] 2018-02-14 19:53
Migrated metadata:
```
Created: 2016-09-06T16:27:56Z
Modified: 2017-10-12T03:02:20Z
```

**Comment by sebu06** [comment] 2021-08-28 08:52
This might be fixed by #2588 - I cannot really reproduce, since it seems that the backslashes in the description were not merged to github.

**Comment by tbabej** [comment] 2021-08-29 03:34
I agree, I think this is actually a duplicate. The description matches the underlying problem exactly (and in the previous versions, this would corrupt the data files).

**Comment by tbabej** [comment] 2021-08-29 03:35
Duplicate of #2189.

**Closed by tbabej** 2021-08-29 03:34 UTC
Labels: bug
