### ISSUE TITLE
It's possible to add a task with invalid due date

### ISSUE THREAD

**Issue by zarelit** [GothenburgBitFactory/taskwarrior#3639] opened 2024-10-01 15:40 UTC
I think I found issue #2996  has repercussion in the command line usage, not only in the tests.

Since the date error is not caught immediately by `task add`, I receive it when I try the `next` report.

> [zarel@tantra:~]$ task add due:2 test
Created task 5.

> [zarel@tantra:~]$ task
'2' is not a valid date in the '' format.

@djmitche The error message is the same of the one in #2996  but I opened another issue because this directly affects the user. 

Output of `task diag`:
```
task 3.1.0
   Platform: Linux

Compiler
    Version: 13.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.6
    libuuid: libuuid + uuid_unparse_lower
 Build type: Release

Configuration
       File: /home/zarel/.config/task/taskrc (found), 72 bytes, mode 100644
       Data: /home/zarel/.local/share/task (found), dir, mode 40755
         GC: Enabled
    $EDITOR: nvim
Hooks
     System: Enabled
   Location: /home/zarel/.local/share/task/hooks
             (-none-)

Tests
   Terminal: 203x66
 Broken ref: Scanned 12 tasks for broken references:
             No broken references found
```

**Comment by djmitche** [comment] 2024-10-02 00:20
Thanks! I agree this is different from #2996, but I think it's a duplicate of #3444.

**Closed as not planned by djmitche** 2024-10-02 00:20 UTC
