### ISSUE TITLE
The report has a minimum width of 222 and does not fit in the available width of 205

### ISSUE THREAD

**Issue by ccaneke** [GothenburgBitFactory/taskwarrior#2260] opened 2020-04-24 15:49 UTC
* What command(s) did you run?
`task next`, `task list`and any other report causes this error except the `newest` report
* What did you expect to happen?
reports to show normal output
* What actually happened?
The output does not fit into the screen and the lines are no longer single spaced.

This happens on two different operating systems and also on two different terminals. I suspect that tasks with a long description and lots of annotations do not fit into the screen.

I have also tried setting `defaultwidth=222` and the issue persists.

**Comment by pbeckingham** [comment] 2020-11-20 23:21
Please reduce your report output to one line only, then provide us with the output of {{task export}} for that one task.

**Comment by tbabej** [comment] 2021-01-17 04:09
@ccaneke Do you still find this issue occurring with 2.5.3 release?

**Comment by Darkstarinternet** [comment] 2021-01-23 15:31
I've just had this problem on 2.5.3 with tasks that have long descriptions. You can do the following as a workaround:

task reportname rc.defaultwidth:120

This increases the number of columns from the default 80 to 120 which solved it for me.

**Comment by tbabej** [comment] 2021-06-27 03:59
I believe this is a duplicate of #2023, which is fixed on 2.5.3 and 2.6.0

**Closed by tbabej** 2021-06-27 03:59 UTC
Labels: awaiting response, bug
