### ISSUE TITLE
Filtering for datetime-like (i.e. "sat") project names fails

### ISSUE THREAD

**Issue by benibilme** [GothenburgBitFactory/taskwarrior#2577] opened 2021-08-19 00:06 UTC
Hello, 

I have not been using taskwarrior for several months. I am using manjaro and I have updated the system many times. taskwarrior might be updated in the process. 

Yesterday, I tried to use taskwarrior.  When try to display specific projects   such as `task pro:sat`, I receive weird messages as below. `aprojectname` sometimes changes. The "aprojectname" has only one task which is overdue about 1.4 year.  I receive this kind of error only when I  query `sat` project. 

`````
[task next ( pro:sat )]
'aprojectname' is not a valid date in the 'Y-M-D' format.
`````
`task diag` output is below

`````
task 2.5.3
   Platform: Linux

Compiler
    Version: 10.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Feb  2 2021 23:45:39
      CMake: 3.19.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.0
 Build type: 

Configuration
       File: /home/xxxxx/.taskrc (found), 2755 bytes, mode 100640
       Data: /home/xxxxx/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: vim
     Server: sssss.xxxxxx.yy:53589
         CA: ~/.task/ca.cert.pem, readable, 3714 bytes
Certificate: ~/.task/xxxxx.cert.pem, readable, 3720 bytes
        Key: ~/.task/xxxxx.key.pem, readable, 24742 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: xxxxx.yy/xxxxx/************************************

Hooks
     System: Enabled
   Location: /home/xxxxx/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 342x76
       Dups: Scanned 435 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 435 tasks for broken references:
             No broken references found
`````
Any help much appreciated.

**Comment by tbabej** [comment] 2021-08-20 12:30
Hi @benibilme,

I was unfortunately unable to reproduce the error. Would you be willing to share the tasks that trigger this, perhaps by running

```
task 1 2 3 export
```

where `1`, `2`, and `3` are the task IDs of the tasks in question? I believe you can modify the description to avoid leaking sensitive data, but the `project:` field value would have to stay intact.

**Comment by benibilme** [comment] 2021-08-20 23:28
Hello,

Thank you for the response.

I am receiving the error when I try to display tasks of a specific project called "sat". When I give following command

`task project:sat`  I received the described error in my initial post  as follows

````
task pro:sat
[task next ( pro:sat )]
'not' is not a valid date in the 'Y-M-D' format.
````


The tasks of the project "sat" is not being displayed. I received error messages from different project without giving a certain task id in the project. I tried to close all task of the complaining projects since I do not know which task creates a problem, then I started to receive the same error from another project. 

I have collected all tasks of project "sat" by `task all | grep sat`  and then I collected the task id by hand and gave the command 

`task id1 id2 id3 export` as you requested. I have anonymized the description parts but I did not touch other sections. 

I have also exported the all tasks of "not" project as well and presented as below. I hope this helps.

**Project Sat Tasks**

````
[
{"id":29,"description":"xxxxxxxxxxxxxx","entry":"20200408T225149Z","modified":"20210819T003412Z","project":"sat","reviewed":"20210819T003412Z","status":"pending","uuid":"4bc00c97-1f4b-43be-a52b-87b69f0792b1","urgency":3},
{"id":30,"description":"xxxxxxxxxxxxxx","entry":"20200408T225154Z","modified":"20210819T003414Z","project":"sat","reviewed":"20210819T003414Z","status":"pending","uuid":"2e1f82d4-2798-44cb-83d9-a6f99b74aec0","urgency":3},
{"id":31,"description":"xxxxxxxxxxxxxx","entry":"20200408T225206Z","modified":"20210819T003416Z","project":"sat","reviewed":"20210819T003416Z","status":"pending","uuid":"7e42a9f2-e195-49c0-9382-172abeffbb89","urgency":3},
{"id":40,"description":"xxxxxxxxxxxxxx","entry":"20200408T230217Z","modified":"20210819T003427Z","project":"sat","reviewed":"20210819T003427Z","status":"pending","uuid":"401b4393-ae62-47e6-b55e-82a76d2f4182","urgency":3},
{"id":43,"description":"xxxxxxxxxxxxxx","entry":"20200408T234633Z","modified":"20210819T003429Z","project":"sat","reviewed":"20210819T003429Z","status":"pending","uuid":"41b19c15-eda7-436f-be13-7a2f47b9a8ad","urgency":3},
{"id":45,"description":"xxxxxxxxxxxxxx","entry":"20200408T234744Z","modified":"20210819T003434Z","project":"sat","reviewed":"20210819T003434Z","status":"pending","uuid":"93d6ec9c-de56-4151-936f-0521f213d79b","urgency":3},
{"id":46,"description":"xxxxxxxxxxxxxx","entry":"20200408T234820Z","modified":"20210819T003435Z","project":"sat","reviewed":"20210819T003435Z","status":"pending","uuid":"141fa967-a7e1-4c3d-ae37-355fa39b78f2","urgency":3},
{"id":70,"description":"xxxxxxxxxxxxxx","entry":"20200424T212800Z","modified":"20210105T125958Z","project":"sat","reviewed":"20210105T125958Z","status":"pending","uuid":"5b4a8f46-8588-4d9a-8f37-2222716752ea","urgency":3},
{"id":74,"description":"xxxxxxxxxxxxxx","entry":"20200428T044934Z","modified":"20210105T130020Z","project":"sat","reviewed":"20210105T130020Z","status":"pending","uuid":"3cf72187-20b8-4108-b636-68af2f631ac3","urgency":3}
]
````

**Project Not Tasks**
````
[
{"id":1,"description":"xxxxxxxxxx","entry":"20200406T082648Z","modified":"20210105T053124Z","project":"not","status":"pending","uuid":"84d78f66-3f20-42f7-882a-119dbfb038cd","annotations":[{"entry":"20200416T155342Z","description":"xxxxxxxxxx"}],"urgency":3.8},
{"id":6,"description":"xxxxxxxxxx","entry":"20200407T223819Z","modified":"20210105T053124Z","project":"not","status":"pending","uuid":"dfa044c0-b05a-492a-8ee1-f4909cb64773","annotations":[{"entry":"20200512T031437Z","description":"xxxxxxxxxx"}],"urgency":3.8},
{"id":7,"description":"xxxxxxxxxx","entry":"20200407T224008Z","modified":"20210105T125725Z","project":"not","reviewed":"20210105T125725Z","status":"pending","uuid":"a4c8d9ad-05e7-4d73-a98e-f77300e4e5b4","urgency":3},
{"id":8,"description":"xxxxxxxxxx","entry":"20200407T230549Z","modified":"20210105T125727Z","project":"not","reviewed":"20210105T125727Z","status":"pending","uuid":"9488d1cb-c600-4846-9907-c166f038e37f","urgency":3},
{"id":38,"description":"xxxxxxxxxx","entry":"20200408T225915Z","modified":"20210105T125737Z","project":"not","reviewed":"20210105T125737Z","status":"pending","uuid":"c9a156d4-5746-4264-a9d9-ecc9e4005718","urgency":3},
{"id":39,"description":"xxxxxxxxxx","entry":"20200408T225941Z","modified":"20210105T125739Z","project":"not","reviewed":"20210105T125739Z","status":"pending","uuid":"17e75e23-c752-4366-8bb9-cbc7f2b11298","urgency":3},
{"id":48,"description":"xxxxxxxxxx","entry":"20200409T134056Z","modified":"20210105T125735Z","project":"not","reviewed":"20210105T125735Z","status":"pending","uuid":"0fd60c06-1758-49d6-ad09-bc093eda5313","urgency":3},
{"id":49,"description":"xxxxxxxxxx","entry":"20200410T081621Z","modified":"20210105T053124Z","project":"not","status":"pending","uuid":"658a2771-fbc6-4348-8fdf-57b67b960fd5","annotations":[{"entry":"20200427T121148Z","description":"xxxxxxxxxx"}],"urgency":3.8},
{"id":61,"description":"xxxxxxxxxx","entry":"20200415T105704Z","modified":"20210105T125729Z","project":"not","reviewed":"20210105T125729Z","status":"pending","uuid":"2a839802-2a48-4e2f-bdf7-b94732dc4f1f","urgency":3},
{"id":75,"description":"xxxxxxxxxx","entry":"20200501T070439Z","modified":"20210105T130026Z","project":"not","reviewed":"20210105T130026Z","status":"pending","uuid":"7fac61c4-8430-4baa-b4df-5fd7bcf7022f","urgency":3},
{"id":100,"description":"xxxxxxxxxx","entry":"20201214T183134Z","modified":"20201214T183134Z","project":"not","status":"pending","uuid":"e398158e-0729-4963-afce-59a22970f17f","urgency":2.36438},
{"id":110,"description":"xxxxxxxxxx","entry":"20210105T051405Z","modified":"20210105T051405Z","project":"not","status":"pending","uuid":"2eee1ba6-635a-430d-9b09-7b816d3ddc54","urgency":2.24384},
]
````
Another observation:

**Although I can not display task of project `sat` but I can always  displays the tasks of the project reported in the error message, in this case project `not` via `task project:not`**

**Comment by tbabej** [comment] 2021-08-21 13:24
Thank you @benibilme, I can now reproduce this on 2.5.3 :slightly_smiling_face:

**Comment by tbabej** [comment] 2021-08-21 13:40
Turns out this was already fixed on 2.6.0 in #2405 and should be fixed for you if you upgrade in the coming weeks!

**Comment by tbabej** [comment] 2021-08-21 13:41
Previously reported as #2386.

**Closed by tbabej** 2021-08-21 13:40 UTC
Labels: bug

**Comment by benibilme** [comment] 2021-08-21 18:42
I have downloaded latest 2.5.3 from git and build it. But the problem continue. Do you mean, I need to wait 2.6.0 version to see the fix?

**Comment by tbabej** [comment] 2021-08-21 18:44
The problem is fixed on the 2.6.0 branch, so you'll need to checkout 2.6.0 and build from there.

**Comment by benibilme** [comment] 2021-08-21 19:02
Okay, I removed the release package, build the 2.6.0 branch, it is working know. Even though I am using manjaro, I believe it will take months to see 2.6.0 on package management system. Thank you for the responses, and for this beautiful software.

**Comment by tbabej** [comment] 2021-08-21 19:19
No worries, glad to see you're enjoying our project!
