### ISSUE TITLE
Better `task undo` confirmation display

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3599] opened 2024-08-14 12:39 UTC
The `confirm_revert` method currently shows a sequence of operations.

https://github.com/GothenburgBitFactory/taskwarrior/blob/70632b088e94a6babe21526ecde22044fbfc16ca/src/TDB2.cpp#L242

This is accurate, but not how users really consider their changes to be made. Rewrite this to be more user-friendly and similar to the 2.6.2 output:

https://github.com/GothenburgBitFactory/taskwarrior/blob/7400e6ed6ba38358000fd5a30cc31db183294d74/src/TDB2.cpp#L1017

**Comment by ryneeverett** [comment] 2024-08-14 15:48
Duplicate of #3371.

**Closed as not planned** 2024-08-14 18:33 UTC
Labels: good first issue
