### ISSUE TITLE
Unable to use ranges for some tasks with IDs above 1000

### ISSUE THREAD

**Issue by manuelhaussmann** [GothenburgBitFactory/taskwarrior#2639] opened 2021-10-18 10:46 UTC
I recently reached 1000+ active tasks (yes, I know I should be more productive/do a thorough review of old tasks) and stumbled across the following problem:
Running `task 1000-1001` yields `No matches.` This is independent of the interval length, as long as start and end are above 1000. 

However, listing the tasks explicitly as `task 1000,1001` works as desired. Similarly starting the interval below 1000 (e.g. `task 999-1001`), ending the interval below 1000 (e.g. `task 1000-999`), or combining it with another explicit task, e.g. `task X,1000-1001` all give the correct output. Whether `X` is below or above 1000 is irrelevant here, it works in either case. However it does not work if the order is switched, i.e. the interval is posted first as `task 1000-1001,X` 

The version I tested this with is 2.6.0. Can't say whether this is a new problem as I never came even close to 1000 in the 2.5.* era.

**Comment by tbabej** [comment] 2021-10-18 23:17
Good find :slightly_smiling_face: thanks for pressure testing TW!

I was able to reproduce this (fyi, this was a problem also prior to 2.6), but since improving parser corner cases was one of the objectives for the release, we will ship the fix for this in 2.6.1.

**Closed as completed** 2021-10-19 04:09 UTC
Labels: type:bug, needs test, eval:reproduced
