### ISSUE TITLE
[UX] 'sometag' shows only pending, but 'sometag mod' modifies complete as well

### ISSUE THREAD

**Issue by Skrylar** [GothenburgBitFactory/taskwarrior#2072] opened 2018-11-03 02:18 UTC
It seems a little inconsistent that typing: `task sometag` shows only pending tasks, but `task sometag mod -sometag +othertag` also sweeps in tasks which have been marked completed. This modification also triggers a cascading message that you should "consider changing the task to pending," even though it was not obvious from the command that already archived tasks would be changed as well.

The naive expectation would be that only things that running the filter might show, are the things which might be modified.

Adding "and status:pending" when doing bulk modifications gets around the problem, but it _is_ yet one more thing to have to keep in mind.

**Comment by pbeckingham** [comment] 2018-12-12 22:53
This doesn't make sense.  Do you mean ``task +sometag ``?

**Comment by tbabej** [comment] 2019-01-02 22:36
@Skrylar this is just because by default you're using the `next` command, which has `+PENDING` default filter that filters out the completed tasks.

Use `task <query> all` to list all tasks matching a given query.

Closing - this works as intended, making `mod` have default `+PENDING` context would only have us implement another flag for it to not apply it :)

**Closed by tbabej** 2019-01-02 22:36 UTC

**Comment by Skrylar** [comment] 2019-01-03 07:02
I'm aware of "why" it happens. I was reporting that the user experience is
bad (two primitive operations operate on two separate contexts and they
aren't directly telling the user that they have to.) If you don't pour over
the docs to figure this out, the program just operates on more than an
"average user" would expect.
